'use client';
import Header from '@/features/shared/components/Header';
import { SoundController } from '@/features/shared/components/SoundController';
import Link from 'next/link';
import { useBi } from '@/lib/i18n/Bilingual';
import ArticleShell from '@/features/blog/components/ArticleShell';
import { ARTICLE_SEO_META } from '@/features/blog/data/articleSeoMetadata';

const META = ARTICLE_SEO_META['panch-mahabhutas-five-elements'];

export default function BlogPage() {
  const bi = useBi();
  return (
    <>
      <SoundController />
      <Header />
      
        <article className="pt-28 pb-20 min-h-screen">

          <section className="relative py-16 sm:py-24 overflow-hidden bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-2)]/95 mb-12">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(168,85,247,0.10),transparent_60%)]" />
            <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/40 to-transparent" />
            <div className="absolute bottom-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/40 to-transparent" />
            <div className="container mx-auto px-4 sm:px-6 relative z-10">
              <div className="absolute top-0 right-4 sm:right-10 w-28 h-28 sm:w-36 sm:h-36 opacity-25 pointer-events-none">
                <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                  <rect x="15" y="15" width="70" height="70" fill="none" stroke="#A855F7" strokeWidth="1.2" opacity="0.5"/>
                  <circle cx="50" cy="50" r="28" fill="none" stroke="#E8B960" strokeWidth="1" opacity="0.5"/>
                  <circle cx="50" cy="50" r="14" fill="none" stroke="#FF9933" strokeWidth="0.8" opacity="0.4"/>
                  <line x1="15" y1="50" x2="85" y2="50" stroke="#A855F7" strokeWidth="0.4" opacity="0.3"/>
                  <line x1="50" y1="15" x2="50" y2="85" stroke="#A855F7" strokeWidth="0.4" opacity="0.3"/>
                  <circle cx="50" cy="50" r="44" fill="none" stroke="#E8B960" strokeWidth="0.7" opacity="0.3">
                    <animateTransform attributeName="transform" type="rotate" from="0 50 50" to="360 50 50" dur="35s" repeatCount="indefinite"/>
                  </circle>
                </svg>
              </div>
              <Link href="/insights" className="inline-flex items-center text-prakash-gold hover:text-sacred-saffron mb-4 text-sm transition-colors">
                <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7"/></svg>
                {bi('Back to Archives', 'संग्रह पर वापस जाएँ')}
              </Link>
              <div className="flex items-center gap-3 text-sm text-[var(--color-hero-fg)]/50 mb-4">
                <span className="bg-purple-500/20 text-purple-300 px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider">{bi('Vastu Science', 'वास्तु विज्ञान')}</span>
                <span className="w-1 h-1 bg-[var(--color-bg-glass)] rounded-full" /><span>{bi('10 min read', '10 मिनट का पठन')}</span>
                <span className="w-1 h-1 bg-[var(--color-bg-glass)] rounded-full" /><span>{bi('By AstroVastu Expert KK Nagaich', 'एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा')}</span>
              </div>
              <h1 className="font-serif text-3xl sm:text-4xl md:text-5xl lg:text-6xl text-[var(--color-hero-fg)] leading-tight mb-4">
                {bi('Understanding the Panch Mahabhutas —', 'पंच महाभूतों को समझें —')}{' '}
                <span className="bg-gradient-to-r from-purple-400 via-prakash-gold to-sacred-saffron bg-clip-text text-transparent">{bi('The Five Elements of Vastu', 'वास्तु के पाँच तत्व')}</span>
              </h1>
              <p className="text-lg text-[var(--color-hero-fg)]/60 max-w-3xl">{bi('A deep dive into earth, water, fire, air, and space — the cosmic building blocks that govern every direction, every room, and every aspect of your life — validated by peer‑reviewed Ayurvedic research, quantum field theory, and the ancient texts.', 'पृथ्वी, जल, अग्नि, वायु और आकाश में गहन प्रवेश — वे ब्रह्मांडीय निर्माण-इकाइयाँ जो हर दिशा, हर कमरे और आपके जीवन के हर पक्ष को संचालित करती हैं — समकक्ष-समीक्षित आयुर्वेदिक शोध, क्वांटम फील्ड थ्योरी और प्राचीन ग्रंथों द्वारा प्रमाणित।')}</p>
            </div>
          </section>

          <ArticleShell
            readingMinutes={META.readingMinutes}
            category={META.category}
            categoryHi={META.categoryHi}
            quickAnswer={META.quickAnswer}
            quickAnswerHi={META.quickAnswerHi}
            toc={META.toc}
            references={META.references}
            faqs={META.faqs}
            related={META.related}
            datePublished="2026-09-30"
            dateModified="2026-10-06"
          >
          <div className="container mx-auto px-4 sm:px-6 max-w-4xl"><div className="prose prose-lg prose-stone max-w-none">

<p className="lead text-xl text-nidra-indigo/70 leading-relaxed">{bi('The Taittiriya Upanishad (1.1.1) declares: "Earth, Water, Fire, Air, and Space — these are the five great elements." Long before Dmitri Mendeleev organised the periodic table in 1869, and millennia before quantum field theory described energy condensing into matter, the Vedic Rishis had already mapped the universe into five fundamental states of existence called the ', 'तैत्तिरीय उपनिषद (1.1.1) घोषणा करता है: "पृथ्वी, जल, अग्नि, वायु और आकाश — ये पाँच महाभूत हैं।" बहुत पहले, जब दिमित्री मेंदलेव ने 1869 में आवर्त सारणी व्यवस्थित की, और सहस्रों वर्ष पहले जब क्वांटम फील्ड थ्योरी ने ऊर्जा के द्रव्य में संघनित होने का वर्णन किया — वैदिक ऋषि पहले ही ब्रह्मांड को पाँच मौलिक अस्तित्व-अवस्थाओं में मानचित्रित कर चुके थे, जिन्हें कहा गया ')}<strong>{bi('Pancha Mahabhutas', 'पाँच महाभूत')}</strong>{bi('. These are not simplistic physical substances. As the Sanatana & Science research portal explains, they are "states of existence, vibrational fields, and layers of consciousness" that map remarkably well to modern atomic theory — with Akasha (Space) corresponding to the quantum vacuum, Vayu (Air) to electromagnetic fields, Agni (Fire) to thermodynamic transformations, Jala (Water) to fluid dynamics and plasma states, and Prithvi (Earth) to solid‑state matter and crystalline lattices. This article presents the definitive Vastu framework for understanding and balancing the five elements — grounded in peer‑reviewed science, ancient Sanskrit texts, and two decades of clinical practice by AstroVastu Expert K.K. Nagaich.', '। ये सरल भौतिक पदार्थ नहीं। सनातन एंड साइंस रिसर्च पोर्टल के अनुसार ये "अस्तित्व की अवस्थाएँ, कम्पन-क्षेत्र और चेतना की परतें" हैं, जो आधुनिक परमाणु सिद्धांत से आश्चर्यजनक रूप से मेल खाती हैं — आकाश (Space) क्वांटम निर्वात के, वायु (Air) विद्युत-चुम्बकीय क्षेत्रों के, अग्नि (Fire) ऊष्मागतिकीय रूपांतरणों के, जल (Water) तरल-गतिशास्त्र और प्लाज़्मा अवस्थाओं के, तथा पृथ्वी (Earth) ठोस-पदार्थ और स्फटिक-जालकों के अनुरूप। यह लेख पाँच तत्वों को समझने और संतुलित करने का निर्णायक वास्तु फ्रेमवर्क प्रस्तुत करता है — समकक्ष-समीक्षित विज्ञान, प्राचीन संस्कृत ग्रंथों और एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच के दो दशकों के क्लीनिकल अनुभव पर आधारित।')}</p>

{/* SECTION 1 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-purple-400 to-indigo-500" /><h2 id="introduction" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('The Pancha Mahabhutas — A Complete Reference Table', 'पाँच महाभूत — पूर्ण संदर्भ सारणी')}</h2></div>
<p>{bi('Every Vastu principle — from room placement to colour therapy, from yantra installation to daily ritual — is ultimately a technique for balancing these five elements. Each element governs a specific direction, a planet, a sensory organ, a bodily function, and a set of life outcomes. The table below synthesises data from the peer‑reviewed Panchamahabhuta Siddhanta study (2025), the CCC–AAA Architects\u2019 Vastu manual, and the JyotishGram elemental imbalance research (2026).', 'हर वास्तु सिद्धांत — कमरे के स्थान से रंग थेरेपी, यंत्र स्थापना से दैनिक अनुष्ठान — अंततः इन पाँच तत्वों को संतुलित करने की विधि है। हर तत्व एक विशिष्ट दिशा, ग्रह, इंद्रिय, शारीरिक क्रिया और जीवन-परिणामों का स्वामी है। नीचे की सारणी समकक्ष-समीक्षित पंचमहाभूत सिद्धांत अध्ययन (2025), CCC–AAA Architects की वास्तु मैनुअल और JyotishGram के तत्व-असंतुलन शोध (2026) का सार है।')}</p>
<div className="mt-4 overflow-hidden rounded-2xl border border-prakash-gold/15">
<table className="w-full text-xs sm:text-sm"><thead><tr className="bg-gradient-to-r from-purple-500/10 to-prakash-gold/10"><th className="py-3 px-2 sm:px-4 text-left font-serif text-nidra-indigo">{bi('Element', 'तत्व')}</th><th className="py-3 px-2 sm:px-4 text-left font-serif text-nidra-indigo">{bi('Direction', 'दिशा')}</th><th className="py-3 px-2 sm:px-4 text-left font-serif text-nidra-indigo">{bi('Planet', 'ग्रह')}</th><th className="py-3 px-2 sm:px-4 text-left font-serif text-nidra-indigo">{bi('Sense', 'इंद्रिय')}</th><th className="py-3 px-2 sm:px-4 text-left font-serif text-nidra-indigo">{bi('Body Part', 'शरीर-अंग')}</th><th className="py-3 px-2 sm:px-4 text-left font-serif text-nidra-indigo">{bi('Life Domain', 'जीवन-क्षेत्र')}</th></tr></thead><tbody>
{[[['Earth (Prithvi)','पृथ्वी (Prithvi)'],['Southwest','दक्षिण-पश्चिम'],['Rahu','राहु'],['Smell','गंध'],['Bones, muscles','हड्डियाँ, मांसपेशियाँ'],['Stability, finances, relationships','स्थिरता, वित्त, संबंध']],[['Water (Jal)','जल (Jal)'],['Northeast','उत्तर-पूर्व'],['Moon','चंद्र'],['Taste','स्वाद'],['Blood, fluids','रक्त, द्रव'],['Emotions, clarity, wealth flow','भावनाएँ, स्पष्टता, धन-प्रवाह']],[['Fire (Agni)','अग्नि (Agni)'],['Southeast','दक्षिण-पूर्व'],['Sun, Mars','सूर्य, मंगल'],['Sight','दृष्टि'],['Metabolism, eyes','चयापचय, आँखें'],['Energy, ambition, digestive health','ऊर्जा, महत्वाकांक्षा, पाचन स्वास्थ्य']],[['Air (Vayu)','वायु (Vayu)'],['Northwest','उत्तर-पश्चिम'],['Saturn','शनि'],['Touch','स्पर्श'],['Lungs, nerves','फुफ्फुस, तंत्रिकाएँ'],['Communication, movement, networking','संचार, गति, नेटवर्किंग']],[['Space (Akash)','आकाश (Akash)'],['Center (Brahmasthan)','केंद्र (ब्रह्मस्थान)'],['Jupiter','बृहस्पति'],['Hearing','श्रवण'],['Brain, consciousness','मस्तिष्क, चेतना'],['Expansion, wisdom, spiritual growth','विस्तार, ज्ञान, आध्यात्मिक वृद्धि']],].map((r,i)=>(<tr key={i} className={`border-t border-prakash-gold/10 ${i%2===0?'bg-[var(--color-bg-glass)]':'bg-vastu-stone/20'}`}>{r.map((c,j)=><td key={j} className={`py-3 px-2 sm:px-4 ${j===0?'font-medium text-nidra-indigo/80':j===1?'text-prakash-gold font-medium':j===5?'text-nidra-indigo/60':'text-nidra-indigo/50'}`}>{bi(c[0], c[1])}</td>)}</tr>))}</tbody></table></div>
<p className="mt-3 text-xs text-nidra-indigo/40">{bi('Sources: Dr. Kunal ojha et al., "Panchamahabhuta Siddhanta: A Review," AJPRI, 2025; JyotishGram, "Vastu and the Five Elements," 2026; CCC–AAA Architects Vastu Manual, 2025; Sanatana & Science, "The 5 Elements & Atomic Science," 2025.', 'स्रोत: Dr. Kunal ojha et al., "Panchamahabhuta Siddhanta: A Review," AJPRI, 2025; JyotishGram, "Vastu and the Five Elements," 2026; CCC–AAA Architects Vastu Manual, 2025; Sanatana & Science, "The 5 Elements & Atomic Science," 2025.')}</p>
</div>

{/* SECTION 2 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-amber-600 to-brown-700" /><h2 id="earth" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('Prithvi (Earth) — The Element of Stability, Southwest', 'पृथ्वी (Prithvi) — स्थिरता का तत्व, दक्षिण-पश्चिम')}</h2></div>
<p>{bi('Earth is the heaviest element — associated with the Southwest (Nairutya) direction, ruled by Rahu, and connected to the sense of smell, bones, and muscles. Prithvi provides the structural integrity of both the physical building and the psychological stability of its residents. According to Housing.com, "The southwest receives the most stable solar radiation during the day, making it ideal for heavy structures and master bedrooms." Vastu Solutions notes that the Southwest quadrant "also receives the strongest infrared radiation from the setting sun, providing sustained thermal mass that releases heat slowly through the night."', 'पृथ्वी सबसे भारी तत्व — दक्षिण-पश्चिम (नैर्ऋत्य) दिशा से संबद्ध, राहु द्वारा शासित, और गंध-इंद्रिय, हड्डियों तथा मांसपेशियों से जुड़ा। पृथ्वी भौतिक भवन की संरचनात्मक अखंडता और निवासियों की मनोवैज्ञानिक स्थिरता दोनों प्रदान करती है। Housing.com के अनुसार, "दक्षिण-पश्चिम दिन में सर्वाधिक स्थिर सौर विकिरण प्राप्त करता है, जिससे वह भारी संरचनाओं और मास्टर बेडरूम के लिए आदर्श बनता है।" Vastu Solutions के अनुसार दक्षिण-पश्चिम चतुर्थांश "अस्तगामी सूर्य का सर्वाधिक प्रबल अवरक्त विकिरण भी प्राप्त करता है, जो निरंतर तापीय द्रव्यमान देकर रातभर मंद-मंद ऊष्मा छोड़ता है।"')}</p>
<p>{bi('Scientific parallel: In modern physics, Earth corresponds to solid‑state matter — atomic lattices, crystalline structures, and gravity‑influenced mass. The Sanatana & Science portal maps Prithvi directly to "solid matter, atomic lattice, crystalline structure, gravity‑affected mass."', 'वैज्ञानिक साम्य: आधुनिक भौतिकी में पृथ्वी ठोस-अवस्था के पदार्थ के अनुरूप — परमाणु-जालक, स्फटिक संरचनाएँ और गुरुत्वाकर्षण-प्रभावित द्रव्यमान। सनातन एंड साइंस पोर्टल पृथ्वी को सीधे "ठोस पदार्थ, परमाणु जालक, स्फटिक संरचना, गुरुत्व-प्रभावित द्रव्यमान" से जोड़ता है।')}</p>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
<div className="p-4 bg-green-50/50 rounded-2xl border border-green-200"><h3 className="font-serif text-base text-green-800 font-bold mb-2">{bi('Balanced Earth', 'संतुलित पृथ्वी')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Financial stability & steady career growth','• वित्तीय स्थिरता और निरंतर करियर-वृद्धि')}</li><li>{bi('• Emotional grounding & secure relationships','• भावनात्मक स्थिरता और सुरक्षित संबंध')}</li><li>{bi('• Strong decision‑making ability','• दृढ़ निर्णय-क्षमता')}</li><li>{bi('• Deep, restful sleep (SW master bedroom)','• गहरी, सुखद नींद (दक्षिण-पश्चिम मास्टर बेडरूम')}</li></ul></div>
<div className="p-4 bg-red-50/50 rounded-2xl border border-red-200"><h3 className="font-serif text-base text-red-800 font-bold mb-2">{bi('Imbalanced Earth', 'असंतुलित पृथ्वी')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Frequent relocations or career instability','• बार-बार स्थानांतरण या करियर-अस्थिरता')}</li><li>{bi('• Weak decision‑making & restlessness','• कमजोर निर्णय-क्षमता और बेचैनी')}</li><li>{bi('• Financial leakage despite good income','• अच्छी आय के बावजूद धन-क्षरण')}</li><li>{bi('• Feelings of uncertainty & insecurity','• अनिश्चितता और असुरक्षा की भावना')}</li></ul></div></div>
<p className="mt-3 text-sm"><strong>{bi('Remedy:', 'उपचार:')}</strong> {bi('Keep the SW heavy — solid furniture, storage units, a ceramic pot with soil. Use beige, brown, or earthy tones. Never place a water tank or toilet here. CCC–AAA Architects (2025) recommends "heavy furniture or storage units here to enhance stability."', 'दक्षिण-पश्चिम को भारी रखें — ठोस फर्नीचर, स्टोरेज यूनिट, मिट्टी वाला सेरामिक गमला। बेज, भूरे या पृथ्वी-से रंग अपनाएँ। यहाँ पानी की टंकी या टॉयलेट कभी न रखें। CCC–AAA Architects (2025) भी "स्थिरता बढ़ाने हेतु यहाँ भारी फर्नीचर या स्टोरेज यूनिट" की सिफारिश करते हैं।')}</p></div>

{/* SECTION 3 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-cyan-400 to-blue-600" /><h2 id="water" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('Jal (Water) — Flow, Prosperity, Northeast', 'जल (Jal) — प्रवाह, समृद्धि, उत्तर-पूर्व')}</h2></div>
<p>{bi('The Northeast (Ishanya) is governed by Water, ruled by the Moon, and associated with taste, blood, and emotional well‑being. The Culture & Heritage portal explains: "Water (Jala) — Symbolic of life, it is associated with the north‑east." This direction is considered the most sacred because it combines the beneficial energies of both North (Kuber\u2019s wealth) and East (Surya\u2019s health). The Northeast must remain open, clean, well‑lit, and never burdened by toilets, kitchens, or heavy storage.', 'उत्तर-पूर्व (ईशान्य) जल का शासित क्षेत्र, चंद्रमा-शासित, और स्वाद, रक्त तथा भावनात्मक सुख से संबद्ध। Culture & Heritage पोर्टल स्पष्ट करता है: "जल (Jala) — जीवन का प्रतीक, उत्तर-पूर्व से जुड़ा।" यह दिशा सर्वाधिक पवित्र मानी जाती है, क्योंकि यह उत्तर (कुबेर के धन) और पूर्व (सूर्य के स्वास्थ्य) — दोनों की लाभकारी ऊर्जाओं का संगम है। उत्तर-पूर्व को खुला, स्वच्छ, सुप्रकाशित रखना चाहिए, टॉयलेट, रसोई या भारी भंडारण का बोझ कभी नहीं देना चाहिए।')}</p>
<p>{bi('Scientific parallel: Water corresponds to fluid dynamics, plasma states, and hydrogen bonding — essential to life and chemical transport. The ArtFactory notes that "Water bodies regulate humidity, create calmness, and reflect light. Water features improve emotional and psychological well‑being."', 'वैज्ञानिक साम्य: जल तरल-गतिशास्त्र, प्लाज़्मा अवस्थाओं और हाइड्रोजन-आबंधन के अनुरूप — जीवन और रासायनिक परिवहन के लिए आवश्यक। The ArtFactory कहता है: "जल-निकाय आर्द्रता नियंत्रित करते हैं, शांति रचते हैं और प्रकाश परावर्तित करते हैं। जल-विशेष भावनात्मक तथा मानसिक सुख बढ़ाते हैं।"')}</p>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
<div className="p-4 bg-green-50/50 rounded-2xl border border-green-200"><h3 className="font-serif text-base text-green-800 font-bold mb-2">{bi('Balanced Water', 'संतुलित जल')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Smooth cash flow & financial opportunities','• सुगम नकदी-प्रवाह और वित्तीय अवसर')}</li><li>{bi('• Emotional clarity & mental calm','• भावनात्मक स्पष्टता और मन की शांति')}</li><li>{bi('• Enhanced creativity & intuition','• बढ़ी रचनात्मकता और अंतर्ज्ञान')}</li><li>{bi('• Spiritual receptivity','• आध्यात्मिक ग्रहणशीलता')}</li></ul></div>
<div className="p-4 bg-red-50/50 rounded-2xl border border-red-200"><h3 className="font-serif text-base text-red-800 font-bold mb-2">{bi('Imbalanced Water', 'असंतुलित जल')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Financial leakage (JyotishGram, 2026)','• धन-क्षरण (JyotishGram, 2026')}</li><li>{bi('• Anxiety, emotional confusion','• चिंता, भावनात्मक द्वंद्व')}</li><li>{bi('• Lack of mental clarity','• मानसिक स्पष्टता का अभाव')}</li><li>{bi('• Stagnant opportunities','• जमे, स्थिर अवसर')}</li></ul></div></div>
<p className="mt-3 text-sm"><strong>{bi('Remedy:', 'उपचार:')}</strong> {bi('Keep a copper vessel with fresh water and rose petals in the NE, changed daily. A small fountain amplifies prosperity. Housivity (2025) recommends "a small indoor fountain or aquarium in the northeast corner. Avoid red or dark colours here."', 'उत्तर-पूर्व में गुलाब की पंखुड़ियों सहित ताजे पानी का तांबे का बर्तन रखें, रोज़ बदलें। छोटा फव्वारा समृद्धि को और बढ़ाता है। Housivity (2025) सिफारिश करता है: "उत्तर-पूर्व कोने में छोटा इनडोर फव्वारा या एक्वेरियम। यहाँ लाल या गहरे रंग वर्जित।"')}</p></div>

{/* SECTION 4 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-orange-500 to-red-600" /><h2 id="fire" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('Agni (Fire) — Energy, Transformation, Southeast', 'अग्नि (Agni) — ऊर्जा, परिवर्तन, दक्षिण-पूर्व')}</h2></div>
<p>{bi('The Southeast (Agneya) is the domain of Fire, ruled by the Sun and Mars, associated with sight, metabolism, and vitality. CCC–AAA Architects (2025) confirm: "Kitchen: Southeast (Agni corner), as it represents fire." The fire element is the driver of ambition — when balanced, it fuels confidence, initiative, and digestive health. When excessive, it creates aggression, conflict, and burnout.', 'दक्षिण-पूर्व (अग्नेय) अग्नि का क्षेत्र, सूर्य और मंगल-शासित, दृष्टि, चयापचय और जीवनशक्ति से संबद्ध। CCC–AAA Architects (2025) पुष्टि करते हैं: "रसोई: दक्षिण-पूर्व (अग्नि-कोना), क्योंकि वह अग्नि का प्रतीक है।" अग्नि तत्व महत्वाकांक्षा का संचालक — संतुलित हो तो आत्मविश्वास, पहल और पाचन-स्वास्थ्य को ईंधन देता; अत्यधिक हो तो आक्रामकता, संघर्ष और थकावट (बर्नआउट) रचता है।')}</p>
<p>{bi('Scientific parallel: Fire corresponds to thermodynamics, photon emission, metabolism, and nuclear fusion. Housing.com observes: "Locating the kitchen in the southeast (fire zone) aligns with the sun\u2019s natural heat, potentially reducing reliance on artificial cooking methods." The Sanatana & Science portal maps Agni to "energy transformations, metabolism, nuclear fusion, thermodynamics, photon emission."', 'वैज्ञानिक साम्य: अग्नि ऊष्मागतिकी, फोटॉन-उत्सर्जन, चयापचय और नाभिकीय संलयन के अनुरूप। Housing.com का कथन: "रसोई को दक्षिण-पूर्व (अग्नि-क्षेत्र) में रखना सूर्य की स्वाभाविक ऊष्मा के साथ संरेखण है, जो संभवतः कृत्रिम खाना पकाने की निर्भरता घटाता है।" सनातन एंड साइंस पोर्टल अग्नि को "ऊर्जा-रूपांतरण, चयापचय, नाभिकीय संलयन, ऊष्मागतिकी, फोटॉन-उत्सर्जन" से जोड़ता है।')}</p>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
<div className="p-4 bg-green-50/50 rounded-2xl border border-green-200"><h3 className="font-serif text-base text-green-800 font-bold mb-2">{bi('Balanced Fire', 'संतुलित अग्नि')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Strong metabolism & vitality','• प्रबल चयापचय और जीवनशक्ति')}</li><li>{bi('• Confidence, drive, leadership','• आत्मविश्वास, उत्प्रेरणा, नेतृत्व')}</li><li>{bi('• Good digestive health','• उत्तम पाचन-स्वास्थ्य')}</li><li>{bi('• Career ambition & recognition','• करियर-महत्वाकांक्षा और पहचान')}</li></ul></div>
<div className="p-4 bg-red-50/50 rounded-2xl border border-red-200"><h3 className="font-serif text-base text-red-800 font-bold mb-2">{bi('Imbalanced Fire', 'असंतुलित अग्नि')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Anger issues, family conflicts','• क्रोध-समस्याएँ, पारिवारिक कलह')}</li><li>{bi('• Digestive problems & acidity','• पाचन-समस्याएँ और अम्लता')}</li><li>{bi('• Low motivation or burnout','• कम उत्प्रेरणा या थकावट')}</li><li>{bi('• JyotishGram: "Excess fire agitates; weak fire reduces drive"','• JyotishGram: "अति अग्नि उत्ताप देती; मंद अग्नि जोश घटाती है"')}</li></ul></div></div>
<p className="mt-3 text-sm"><strong>{bi('Remedy:', 'उपचार:')}</strong> {bi('A salt lamp in the SE, a ghee lamp lit at sunrise, warm tones (orange, red, yellow). NHS–Spazay (2024) recommends "light orange, red, yellow, and peach to stimulate appetite." Never place water features in this zone.', 'दक्षिण-पूर्व में सॉल्ट लैंप, सूर्योदय पर जलाई घी की दीपक, गर्म रंग (नारंगी, लाल, पीला)। NHS–Spazay (2024) "भूक बढ़ाने हेतु हल्का नारंगी, लाल, पीला और आड़ू रंग" की सिफारिश करता है। इस क्षेत्र में जल-विशेष कभी न रखें।')}</p></div>

{/* SECTION 5 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-sky-300 to-slate-500" /><h2 id="air" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('Vayu (Air) — Movement, Communication, Northwest', 'वायु (Vayu) — गति, संचार, उत्तर-पश्चिम')}</h2></div>
<p>{bi('The Northwest (Vayavya) is governed by Air, ruled by Saturn, and connected to touch, lungs, and nerve impulses. Vayu enables communication, networking, travel, and intellectual agility. The NewsPoint lifestyle portal (2026) explains: "Air is associated with movement, freshness, and communication. It governs the northwest direction and supports circulation, both physically and emotionally."', 'उत्तर-पश्चिम (वाव्य) वायु का शासित क्षेत्र, शनि-शासित, स्पर्श, फुफ्फुस और तंत्रिका-वेग से जुड़ा। वायु संचार, नेटवर्किंग, यात्रा और बौद्धिक चपलता को सक्षम करती है। NewsPoint लाइफस्टाइल पोर्टल (2026) स्पष्ट करता है: "वायु गति, ताज़गी और संचार से जुड़ी है। वह उत्तर-पश्चिम दिशा पर शासक है और भौतिक तथा भावनात्मक — दोनों तरह के परिसंचरण का समर्थन करती है।"')}</p>
<p>{bi('Scientific parallel: Vayu corresponds to the movement of electrons, electromagnetic fields, and force carriers (photons). Proper ventilation in this zone reduces stress, improves air quality, and facilitates social connection. Housivity notes: "Open windows daily, especially in the morning, to allow fresh air to circulate."', 'वैज्ञानिक साम्य: वायु इलेक्ट्रॉनों की गति, विद्युत-चुम्बकीय क्षेत्रों और बल-वाहक कणों (फोटॉन) के अनुरूप। इस क्षेत्र में उचित पवन-संचार तनाव घटाता, वायु-गुणवत्ता सुधारता और सामाजिक जुड़ाव को सरल बनाता है। Housivity: "रोज़ खिड़कियाँ खोलें, विशेषतः सुबह, ताकि ताज़ी हवा बह सके।"')}</p>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
<div className="p-4 bg-green-50/50 rounded-2xl border border-green-200"><h3 className="font-serif text-base text-green-800 font-bold mb-2">{bi('Balanced Air', 'संतुलित वायु')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Smooth communication & networking','• सुगम संचार और नेटवर्किंग')}</li><li>{bi('• Timely project completion','• समय पर परियोजना-पूर्णता')}</li><li>{bi('• Healthy relationships','• स्वस्थ संबंध')}</li><li>{bi('• Mental agility & fresh ideas','• मानसिक चपलता और नए विचार')}</li></ul></div>
<div className="p-4 bg-red-50/50 rounded-2xl border border-red-200"><h3 className="font-serif text-base text-red-800 font-bold mb-2">{bi('Imbalanced Air', 'असंतुलित वायु')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Communication gaps & misunderstandings','• संचार-अंतर और गलतफहमियाँ')}</li><li>{bi('• Project delays & stagnation','• परियोजना-विलंब और जड़ता')}</li><li>{bi('• JyotishGram: "Instability in relationships"','• JyotishGram: "संबंधों में अस्थिरता"')}</li><li>{bi('• Overthinking & mental restlessness','• अति-चिंतन और मानसिक बेचैनी')}</li></ul></div></div>
<p className="mt-3 text-sm"><strong>{bi('Remedy:', 'उपचार:')}</strong> {bi('A metal wind chime with 5‑6 rods in the NW. Ensure good cross‑ventilation. Light, white, or pastel grey colours. Housivity recommends: "Avoid clutter and unused items" in this zone.', 'उत्तर-पश्चिम में 5–6 रॉड वाला धातु का विंड चाइम। अच्छा क्रॉस-वेंटिलेशन सुनिश्चित करें। हल्के, सफ़ेद या पिस्टल-धूसर रंग। Housivity इस क्षेत्र में "अव्यवस्था और अनुपयोगी वस्तुओं से बचें" की सलाह देता है।')}</p></div>

{/* SECTION 6 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-fuchsia-400 to-purple-700" /><h2 id="space" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('Akash (Space) — The Brahmasthan, the Cosmic Center', 'आकाश (Akash) — ब्रह्मस्थान, ब्रह्मांडीय केंद्र')}</h2></div>
<p>{bi('Space (Akasha) is the subtlest element — the void from which all others emerge. It governs the center of the home, the Brahmasthan, and is ruled by Jupiter. The Sanatana & Science portal makes a striking comparison: "Akasha as Quantum Vacuum — The vacuum is not empty; it\u2019s a field full of fluctuations, the base energy field from which all particles arise." This aligns with the Chandogya Upanishad (6.3.4), which describes the cosmic condensation process: "From Akasha arose Vayu, from Vayu Agni, from Agni Apas, from Apas Prithvi" — a five‑thousand‑year‑old description of energy condensing into matter.', 'आकाश (Akasha) सूक्ष्मतम तत्व — वह शून्य जिससे अन्य सब उद्भूत होते हैं। यह घर के केंद्र, ब्रह्मस्थान पर शासक है और बृहस्पति-शासित। सनातन एंड साइंस पोर्टल की तुलना अत्यंत रोचक: "आकाश और क्वांटम निर्वात — निर्वात खाली नहीं; वह उतार-चढ़ाव से परिपूर्ण क्षेत्र है, मूल ऊर्जा-क्षेत्र, जिससे सभी कण प्रकट होते हैं।" यह छान्दोग्य उपनिषद (6.3.4) से मेल खाता है, जो ब्रह्मांडीय संघनन-क्रम वर्णित करता है: "आकाश से वायु, वायु से अग्नि, अग्नि से आप, आप से पृथ्वी" — ऊर्जा के द्रव्य में बदलने का पाँच हज़ार वर्ष पुराना वर्णन।')}</p>
<p>{bi('The Brahmasthan must remain open, unbuilt, and well‑lit. ArtFactory explains: "Open central areas enhance air circulation and spatial perception, lowering stress." JyotishGram (2026) notes: "When blocked: feeling stuck or directionless, overall stagnation, health issues without clear cause."', 'ब्रह्मस्थान को खुला, निर्माण-रहित और सुप्रकाशित रखना चाहिए। ArtFactory स्पष्ट करता है: "खुला केंद्रीय क्षेत्र वायु-परिसंचरण और स्थान-बोधन को बढ़ाकर तनाव घटाता है।" JyotishGram (2026): "अवरोधित होने पर: अटके रहने या दिशाहीनता का भाव, समग्र जड़ता, बिना स्पष्ट कारण स्वास्थ्य-समस्याएँ।"')}</p>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
<div className="p-4 bg-green-50/50 rounded-2xl border border-green-200"><h3 className="font-serif text-base text-green-800 font-bold mb-2">{bi('Balanced Space', 'संतुलित आकाश')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Mental clarity & spiritual growth','• मानसिक स्पष्टता और आध्यात्मिक वृद्धि')}</li><li>{bi('• All‑round harmony','• सर्वार्ंगीण सामंजस्य')}</li><li>{bi('• Creative expansion','• रचनात्मक विस्तार')}</li><li>{bi('• Light‑filled, peaceful atmosphere','• प्रकाशमय, शांत वातावरण')}</li></ul></div>
<div className="p-4 bg-red-50/50 rounded-2xl border border-red-200"><h3 className="font-serif text-base text-red-800 font-bold mb-2">{bi('Blocked Space', 'अवरोधित आकाश')}</h3><ul className="text-sm text-nidra-indigo/60 space-y-1.5"><li>{bi('• Overall life stagnation','• समग्र जीवन में जड़ता')}</li><li>{bi('• Feeling directionless','• दिशाहीनता का अनुभव')}</li><li>{bi('• Unexplained health issues','• अव्याख्यायित स्वास्थ्य-समस्याएँ')}</li><li>{bi('• JyotishGram: "Jupiter governs expansion — blocked space restricts growth on all levels"','• JyotishGram: "बृहस्पति विस्तार का स्वामी — अवरोधित स्थान हर स्तर पर वृद्धि रोक देता है"')}</li></ul></div></div>
<p className="mt-3 text-sm"><strong>{bi('Remedy:', 'उपचार:')}</strong> {bi('Keep the center completely open — no walls, heavy furniture, or storage. A skylight or crystal lotus amplifies cosmic energy. Light, neutral colours.', 'केंद्र पूर्णतः खुला रखें — न दीवारें, न भारी फर्नीचर, न भंडारण। स्काईलाइट या क्रिस्टल कमल कॉस्मिक ऊर्जा को बढ़ाता है। हल्के, उदासीन रंग।')}</p></div>

{/* SECTION 7 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-emerald-400 to-teal-600" /><h2 id="balancing" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('The Vastu Purusha Mandala — The 64‑Square Cosmic Grid', 'वास्तु पुरुष मंडल — 64-वर्गों की ब्रह्मांडीय ग्रिड')}</h2></div>
<p>{bi('The Vastu Purusha Mandala is the sacred geometric diagram upon which all Vastu principles are mapped. It is a square grid of 64 (8×8) or 81 (9×9) equal squares, with 45 deities assigned to specific positions. Each square corresponds to a direction, an element, a body part of the Vastu Purusha (the cosmic being), and a life function. The Culture & Heritage portal describes it as "the metaphysical plan of a building that incorporates cosmic energy and directional alignments." CCC–AAA Architects (2025) adds: "The Vastu Purusha Mandala is a sacred diagram used to plan the layout, dividing the site into a grid."', 'वास्तु पुरुष मंडल वह पवित्र ज्यामितीय चित्र है जिस पर समस्त वास्तु सिद्धांत अंकित हैं। यह 64 (8×8) या 81 (9×9) समान वर्गों की वर्गाकार ग्रिड, जिसमें 45 देवता विशिष्ट स्थानों पर नियुक्त। हर वर्ग एक दिशा, एक तत्व, वास्तु पुरुष (ब्रह्मांडीय पुरुष) के एक शरीरांग और एक जीवन-क्रिया के अनुरूप। Culture & Heritage पोर्टल इसे "भवन का आध्यात्मिक नक्शा, जिसमें ब्रह्मांडीय ऊर्जा और दिशा-संरेखण समाहित" कहता है। CCC–AAA Architects (2025) जोड़ते हैं: "वास्तु पुरुष मंडल एक पवित्र चित्र, लेआउट की योजना हेतु — स्थल को ग्रिड में बाँटकर।"')}</p>
<p>{bi('In this mandala, the Vastu Purusha lies face‑down with his head in the Northeast (Ishanya — the seat of clarity and wisdom), his feet in the Southwest (stability), his right arm in the Southeast (fire/action), and his left arm in the Northwest (air/movement). Each body part governs a specific zone, and aligning design elements with these body parts optimises energy flow — a concept independently validated by the Morphogenesis architectural research group (2025). The 45 deities assigned to the mandala\u2019s squares represent specific cosmic forces, each governing measurable life functions — from career progression to relationship harmony.', 'इस मंडल में वास्तु पुरुष अधोमुख शयित — सिर उत्तर-पूर्व में (ईशान्य — स्पष्टता और ज्ञान का आसन), चरण दक्षिण-पश्चिम में (स्थिरता), दायीं भुजा दक्षिण-पूर्व में (अग्नि/क्रिया), बायीं भुजा उत्तर-पश्चिम में (वायु/गति)। हर शरीरांग एक विशिष्ट क्षेत्र का स्वामी, और डिज़ाइन-तत्वों को इन अंगों के साथ संरेखित करने से ऊर्जा-प्रवाह अनुकूलतम — Morphogenesis आर्किटेक्चरल रिसर्च ग्रुप (2025) द्वारा स्वतंत्र रूप से प्रमाणित अवधारणा। मंडल के वर्गों पर नियुक्त 45 देवता विशिष्ट ब्रह्मांडीय शक्तियों के प्रतीक, हर एक मापनीय जीवन-क्रियाओं का संचालन — करियर-उन्नति से लेकर संबंध-सामंजस्य तक।')}</p></div>

{/* SECTION 8 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-sacred-saffron to-kumkuma-red" /><h2 id="balancing" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('The Human Body — A Living Vastu Mandala', 'मानव शरीर — जीवंत वास्तु मंडल')}</h2></div>
<p>{bi('One of the most profound Vedic insights is that the five elements in the home directly correspond to the five elements in the human body. The Sharecare health portal explains: "Vastu Shastra can benefit your health by balancing the five elements in your home; different corners of your home are connected to different areas of your body." The Ayurvedic connection deepens this: the three doshas (Vata, Pitta, Kapha) are themselves combinations of the five elements — Vata is Air + Space, Pitta is Fire + Water, Kapha is Earth + Water. A Vastu imbalance therefore manifests as both a physical health symptom and a directional defect in the home.', 'सर्वाधिक गहन वैदिक अंतर्दृष्टियों में से एक: घर के पाँच तत्व सीधे मानव शरीर के पाँच तत्वों से अनुरूप। Sharecare स्वास्थ्य पोर्टल स्पष्ट करता है: "वास्तु शास्त्र आपके घर के पाँच तत्वों को संतुलित कर आपके स्वास्थ्य को लाभ दे सकता; घर के विभिन्न कोने शरीर के विभिन्न भागों से जुड़े हैं।" आयुर्वेदिक संबंध इसे और गहरा करता: तीन दोष (वात, पित्त, कफ) स्वयं पाँच तत्वों के संयोग — वात = वायु + आकाश, पित्त = अग्नि + जल, कफ = पृथ्वी + जल। अतः वास्तु-असंतुलन एक साथ शारीरिक स्वास्थ्य-लक्षण और घर की दिशा-त्रुटि — दोनों रूपों में प्रकट होता है।')}</p>
<div className="mt-4 overflow-hidden rounded-2xl border border-prakash-gold/15">
<table className="w-full text-sm"><thead><tr className="bg-gradient-to-r from-sacred-saffron/10 to-kumkuma-red/10"><th className="py-3 px-4 text-left font-serif text-nidra-indigo">{bi('Home Zone', 'घर का क्षेत्र')}</th><th className="py-3 px-4 text-left font-serif text-nidra-indigo">{bi('Element', 'तत्व')}</th><th className="py-3 px-4 text-left font-serif text-nidra-indigo">{bi('Body System', 'शरीर-तंत्र')}</th><th className="py-3 px-4 text-left font-serif text-nidra-indigo">{bi('Imbalance Symptom', 'असंतुलन के लक्षण')}</th></tr></thead><tbody>
{[['Northeast','Water','Brain, nervous system, emotions','Anxiety, confusion, poor decision‑making','उत्तर-पूर्व','जल','मस्तिष्क, तंत्रिका-तंत्र, भावनाएँ','चिंता, भ्रम, निर्णय-क्षमता में कमी'],['Southeast','Fire','Digestive system, eyes, metabolism','Acidity, ulcers, low energy','दक्षिण-पूर्व','अग्नि','पाचन-तंत्र, आँखें, चयापचय','अम्लता, अल्सर, कम ऊर्जा'],['Southwest','Earth','Bones, muscles, immune system','Joint pain, fatigue, insecurity','दक्षिण-पश्चिम','पृथ्वी','हड्डियाँ, मांसपेशियाँ, रोग-प्रतिरोधक तंत्र','जोड़ों का दर्द, थकान, असुरक्षा-भाव'],['Northwest','Air','Lungs, respiratory, social connection','Breathing issues, isolation, communication blocks','उत्तर-पश्चिम','वायु','फुफ्फुस, श्वसन-तंत्र, सामाजिक जुड़ाव','श्वास-समस्याएँ, एकांतवास, संचार-अवरोध'],['Center','Space','Heart, consciousness, overall vitality','Chronic fatigue, sense of being stuck','केंद्र','आकाश','हृदय, चेतना, समग्र प्राणशक्ति','दीर्घकालिक थकान, अटके रहने का भाव'],].map((r,i)=>(<tr key={i} className={`border-t border-prakash-gold/10 ${i%2===0?'bg-[var(--color-bg-glass)]':'bg-vastu-stone/20'}`}><td className="py-3 px-4 font-medium text-nidra-indigo/80">{bi(r[0], r[4])}</td><td className="py-3 px-4 text-prakash-gold font-medium">{bi(r[1], r[5])}</td><td className="py-3 px-4 text-nidra-indigo/60">{bi(r[2], r[6])}</td><td className="py-3 px-4 text-nidra-indigo/50">{bi(r[3], r[7])}</td></tr>))}</tbody></table></div>
<p className="mt-3 text-xs text-nidra-indigo/40">{bi('Sources: Sharecare Health Portal; JyotishGram, "Effects of Elemental Imbalance," 2026; AJPRI Panchamahabhuta Siddhanta Review, 2025; MahaVastu 5,000+ Case Studies.', 'स्रोत: Sharecare Health Portal; JyotishGram, "Effects of Elemental Imbalance," 2026; AJPRI Panchamahabhuta Siddhanta Review, 2025; MahaVastu 5,000+ Case Studies.')}</p></div>

{/* SECTION 9 */}
<div className="mt-12 mb-8"><div className="flex items-center gap-3 mb-6"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-amber-400 to-gold-500" /><h2 id="balancing" className="font-serif text-2xl sm:text-3xl text-nidra-indigo">{bi('Daily Rituals to Balance All Five Elements', 'पाँचों तत्व संतुलित करने के दैनिक अनुष्ठान')}</h2></div>
<div className="mt-4 grid sm:grid-cols-2 gap-4">
{[{element:'Earth',elementHi:'पृथ्वी',ritual:'Place a ceramic bowl of uncrushed sea salt in the SW corner. Replace weekly — discard outside the home. Walk barefoot on natural ground for 10 minutes daily.',ritualHi:'दक्षिण-पश्चिम कोने में बिना कुचले समुद्री नमक का सेरामिक कटोरा रखें। सप्ताह में बदलें — घर के बाहर त्यागें। रोज़ 10 मिनट नंगे पाँव प्राकृतिक मिट्टी पर चलें।'},{element:'Water',elementHi:'जल',ritual:'Change the water in your NE copper vessel every morning before 9 AM. Add a few drops of Gangajal and fresh rose petals. Drink from this vessel throughout the day.',ritualHi:'रोज़ प्रातः 9 बजे से पहले उत्तर-पूर्व के तांबे के बर्तन का पानी बदलें। कुछ बूँद गंगाजल और ताज़ी गुलाब-पंखुड़ियाँ डालें। सारा दिन इसी बर्तन का जल पिएं।'},{element:'Fire',elementHi:'अग्नि',ritual:'Light a ghee lamp (diya) in the SE at sunrise (around 6‑7 AM). Adding two cloves to the ghee is a traditional remedy for family health and digestive wellness.',ritualHi:'सूर्योदय पर (लगभग 6–7 बजे) दक्षिण-पूर्व में घी का दीपक जलाएँ। पारिवारिक स्वास्थ्य और पाचन-सुख हेतु घी में दो लौंग डालना परंपरागत उपचार।'},{element:'Air',elementHi:'वायु',ritual:'Open all windows for at least 15 minutes every morning. A brass or copper wind chime in the NW, sounded gently once daily, activates the air element.',ritualHi:'रोज़ प्रातः सभी खिड़कियाँ कम से कम 15 मिनट खोलें। उत्तर-पश्चिम में पीतल या तांबे का विंड चाइम, रोज़ एक बार मृदु ध्वनि से, वायु-तत्व सक्रिय करता है।'},{element:'Space',elementHi:'आकाश',ritual:'Spend 5 minutes daily in silence at the center of your home. Visualise golden light filling the Brahmasthan and radiating outward to all corners.',ritualHi:'रोज़ 5 मिनट घर के केंद्र में मौन बिताएँ। भावना करें कि सुनहरा प्रकाश ब्रह्मस्थान को भरकर चारों कोनों की ओर फैल रहा है।'},{element:'All Five',elementHi:'पाँचों तत्व',ritual:'Practice the Pancha Bhuta Stuti (prayer to the five elements) each morning. Declutter one zone per day — Monday SW, Tuesday NW, Wednesday NE, Thursday SE, Friday Center.',ritualHi:'प्रत्येक प्रातः पंचभूत स्तुति (पाँचों तत्वों को प्रणाम) का पाठ करें। दिन में एक क्षेत्र अव्यवस्था-मुक्त करें — सोमवार दक्षिण-पश्चिम, मंगलवार उत्तर-पश्चिम, बुधवार उत्तर-पूर्व, गुरुवार दक्षिण-पूर्व, शुक्रवार केंद्र।'},].map((r,i)=>(<div key={i} className="p-4 bg-[var(--color-bg-glass)] rounded-2xl border border-prakash-gold/15"><div className="flex items-center gap-2 mb-2"><div className="w-2 h-2 rounded-full bg-prakash-gold" /><h3 className="font-serif text-base text-nidra-indigo font-bold">{bi(r.element, r.elementHi)}</h3></div><p className="text-sm text-nidra-indigo/70 leading-relaxed">{bi(r.ritual, r.ritualHi)}</p></div>))}</div></div>

{/* CONCLUSION */}
<div className="mt-12 p-8 bg-gradient-to-br from-vastu-stone/30 to-[var(--color-bg-elevated)] rounded-3xl border border-prakash-gold/20"><div className="flex items-center gap-3 mb-4"><div className="h-10 w-1.5 rounded-full bg-gradient-to-b from-purple-400 to-sacred-saffron" /><h2 id="conclusion" className="font-serif text-2xl text-nidra-indigo">{bi('Conclusion — Balance the Five, Balance Your Life', 'निष्कर्ष — पाँच संतुलित, जीवन संतुलित')}</h2></div>
<p>{bi('The Pancha Mahabhutas are not abstract philosophy. They are the operating system of the universe — the same five forces that shape galaxies, govern human physiology, and determine whether you sleep peacefully or fitfully in your own bedroom. The peer‑reviewed Panchamahabhuta Siddhanta study (2025) confirms that these five elements form the bridge between ancient Vedic wisdom and modern biochemistry, anatomy, and pharmacology. The Sanatana & Science portal demonstrates their alignment with quantum field theory. The JyotishGram research (2026) catalogues precisely what happens — in measurable life terms — when each element is imbalanced. And the MahaVastu institute, drawing on over 5,000 case studies, has documented the health transformations that occur when Vastu elements are restored to equilibrium. The question is not whether your home has five‑element imbalances. Every home does. The question is whether you choose to correct them.', 'पाँच महाभूत केवल विमूर्त दर्शन नहीं — ब्रह्मांड का संचालन-तंत्र हैं। वे ही पाँच शक्तियाँ जो आकाशगंगाएँ गढ़ती हैं, मानव शरीर-क्रिया को नियंत्रित करती हैं, और यह तय करती हैं कि आपके अपने बेडरूम में नींद सुखद होगी या विक्षुब्ध। समकक्ष-समीक्षित पंचमहाभूत सिद्धांत अध्ययन (2025) पुष्टि करता है कि ये पाँच तत्व प्राचीन वैदिक प्रज्ञा और आधुनिक जैव-रसायन, शारीरिक-रचना तथा औषधि-शास्त्र के बीच सेतु रचते हैं। सनातन एंड साइंस पोर्टल उनकी क्वांटम फील्ड थ्योरी से अनुरुपता दर्शाता है। JyotishGram शोध (2026) बिल्कुल स्पष्टता से दर्ज करता है — मापनीय जीवन-भाषा में — कि जब हर तत्व असंतुलित होता है तो क्या घटित होता है। और MahaVastu संस्थान ने 5,000 से अधिक केस स्टडीज़ के आधार पर स्वास्थ्य-रूपांतरण प्रलेखित किए, जो तत्वों के संतुलन पुनर्सथापन पर घटित होते। प्रश्न यह नहीं कि आपके घर में पाँच-तत्व असंतुलन हैं या नहीं — हर घर में हैं। प्रश्न यह है कि क्या आप उन्हें सुधारने को चुनते हैं।')}</p>
<p className="font-medium">{bi('AstroVastu Expert K.K. Nagaich provides comprehensive Pancha Mahabhuta analysis as part of every residential and commercial Vastu consultation — identifying elemental imbalances, mapping them to specific health and life outcomes, and prescribing precise, non‑invasive remedies refined over two decades of clinical practice.', 'एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच हर आवासीय एवं वाणिज्यिक वास्तु परामर्श के अंतर्गत समग्र पंचमहाभूत विश्लेषण प्रदान करते — तत्व-असंतुलन चिह्नित, उन्हें विशिष्ट स्वास्थ्य और जीवन-परिणामों से जोड़, और दो दशकों के क्लीनिकल अनुभव से परिष्कृत परिशुद्ध, गैर-आक्रामक उपचार निर्धारित।')}</p></div>

</div>
          </div>
          </ArticleShell>
        </article>

    </>
  );
}
