'use client';
import Header from '@/features/shared/components/Header';
import { SoundController } from '@/features/shared/components/SoundController';
import Link from 'next/link';
import { useBi } from '@/lib/i18n/Bilingual';

export default function PyramidologyPage() {
  const bi = useBi();
  return (
    <>

        {/* ── LOOPING GRADIENT HERO ── */}
        <section className="relative min-h-[85vh] flex items-center justify-center overflow-hidden bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,215,0,0.10),transparent_60%)]" />
          <div className="absolute top-20 left-[8%] w-80 h-80 rounded-full bg-gradient-to-br from-prakash-gold/8 to-transparent backdrop-blur-3xl border border-[var(--color-border-soft)] animate-[float_10s_ease-in-out_infinite]" />
          <div className="absolute bottom-10 right-[5%] w-64 h-64 rounded-full bg-gradient-to-tl from-amber-300/5 to-transparent backdrop-blur-2xl border border-[var(--color-border-soft)] animate-[float_12s_ease-in-out_infinite_reverse]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10 text-center mt-16">
            <span className="text-prakash-gold uppercase tracking-[0.3em] text-xs sm:text-sm mb-4 block font-semibold">{bi('Advance Treatments · उन्नत उपचार', 'उन्नत उपचार')}</span>
            <h1 className="font-serif text-4xl sm:text-5xl md:text-7xl lg:text-8xl text-[var(--color-hero-fg)] mb-6 leading-tight drop-shadow-2xl"><span className="bg-gradient-to-r from-amber-300 via-prakash-gold to-sacred-saffron bg-clip-text text-transparent">{bi('Pyramidology', 'पिरामिड विद्या')}</span></h1>
            <p className="text-base sm:text-lg md:text-xl text-[var(--color-hero-fg)]/70 max-w-3xl mx-auto mb-4 px-4 leading-relaxed">{bi('Copper Pyramid Grids · Brass Pyramid Arrays · Crystal Pyramid Placement · 9‑Pyramid Cosmic Energy Array · Bedroom & Workplace Installations · Dosha Zone Correction · Health & Wealth Amplification', 'कॉपर पिरेमिड ग्रिड · पीतल पिरेमिड सरणी · स्फटिक पिरेमिड स्थापना · नौ-पिरेमिड दिव्य ऊर्जा सरणी · शयनकक्ष एवं कार्यस्थल स्थापना · दोष क्षेत्र सुधार · स्वास्थ्य व धन का वर्धन')}</p>
            <p className="text-sm sm:text-base text-[var(--color-hero-fg)]/50 max-w-2xl mx-auto mb-10">{bi('Sacred pyramid energy correction — performed by AstroVastu Expert K.K. Nagaich, 4th generation Guru, MBA, Ex‑CEO — for homes, offices, factories, and spiritual spaces.', 'पवित्र पिरामिड ऊर्जा सुधार — एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा — 4 पीढ़ियों के गुरु, MBA, पूर्व सीईओ — घरों, कार्यालयों, कारखानों एवं आध्यात्मिक स्थानों हेतु।')}</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/bookings" className="px-10 py-5 bg-gradient-to-r from-amber-500 via-prakash-gold to-sacred-saffron text-nidra-indigo font-bold rounded-full shadow-[0_10px_30px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_45px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Book Pyramid Consultation', 'पिरामिड परामर्श बुक करें')}</Link><Link href="#practices" className="bg-transparent border-2 border-white text-white hover:bg-white/10 px-10 py-5 rounded-full text-lg font-medium">{bi('Explore Practices ↓', 'उपाय जानें ↓')}</Link></div>
          </div>
        </section>

        {/* ── PYRAMID SCIENCE ── */}
        <section className="py-16 sm:py-24 bg-gradient-to-b from-[var(--color-bg-elevated)] via-vastu-stone/10 to-[var(--color-bg-elevated)] relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('The Sacred Geometry of Power', 'शक्ति की पावन ज्यामिति')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Pyramid Architecture – The World\'s Most Powerful Energy‑Amplification Structure', 'पिरामिड संरचना – संसार की सबसे शक्तिशाली ऊर्जा-वर्धक रचना')}</h2><p className="text-nidra-indigo/60 max-w-3xl mx-auto text-sm">{bi('The pyramid shape is a proven energy‑amplification geometry. Copper pyramids are the most powerful non‑structural Vastu remedy — the apex absorbs geopathic forces from all eight directions, stores in its centre, and neutralises effects.', 'पिरामिड आकार एक सिद्ध ऊर्जा-वर्धक ज्यामिति है। ताम्बे के पिरामिड सबसे प्रबल गैर-संरचनात्मक वास्तु उपचार हैं — इनका शिखर आठों दिशाओं की भू-रोगी शक्तियों को अवशोषित करता है, केंद्र में संग्रहित करता है और उनके प्रभाव को निष्प्रभावी कर देता है।')}</p></div>
          </div>
        </section>

        {/* ── 9 SACRED PRACTICES ── */}
        <section id="practices" className="py-16 sm:py-24 bg-[var(--color-bg-elevated)] relative">
          <div className="container mx-auto px-4 sm:px-6 max-w-6xl">
            <div className="text-center mb-14"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Sacred Pyramid Practices', 'पावन पिरामिड उपाय')}</span><h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-nidra-indigo mt-3 mb-4">{bi('Authentic Pyramidology for Vastu Correction & Energy Amplification', 'वास्तु सुधार एवं ऊर्जा वर्धन हेतु प्रामाणिक पिरामिड विद्या')}</h2><p className="text-nidra-indigo/60 max-w-2xl mx-auto text-sm">{bi('Each practice deploys precision‑engineered pyramids — copper for grounding, brass for prosperity, crystal for emotional balance.', 'प्रत्येक उपाय में परिशुद्धता-निर्मित पिरामिड प्रयुक्त होते हैं — ताम्बा स्थिरता हेतु, पीतल समृद्धि हेतु, स्फटिक भावनात्मक संतुलन हेतु।')}</p></div>
            <div className="space-y-16">
              {[
                {num:'01',title:'The 9‑Pyramid Cosmic Energy Array – Whole‑House Correction',titleHi:'नौ-पिरेमिड दिव्य ऊर्जा सरणी – संपूर्ण गृह सुधार',desc:'Nine energised copper pyramids installed at pre‑determined geometric points across the property creating a cosmic energy grid. Centre + 4 corners + 4 entrances. Complete dosha neutralisation. Permanent — no ongoing maintenance.',descHi:'संपत्ति में पूर्व-निर्धारित ज्यामितीय बिंदुओं पर स्थापित नौ ऊर्जावान ताम्बे के पिरामिड दिव्य ऊर्जा का जाल रचते हैं। केंद्र + चार कोण + चार प्रवेश द्वार। पूर्ण दोष निवारण। स्थायी — अनुरक्षण की आवश्यकता नहीं।',features:['9 copper pyramids at geometric points','Centre + 4 corners + 4 entrances','Complete whole‑house dosha neutralisation','Cosmic prana field generation','Permanent — no ongoing maintenance'],featuresHi:['ज्यामितीय बिंदुओं पर 9 ताम्बे के पिरामिड','केंद्र + चार कोण + चार प्रवेश द्वार','संपूर्ण गृह का दोष निवारण','दिव्य प्राण-ऊर्जा क्षेत्र की सृष्टि','स्थायी — अनुरक्षण की आवश्यकता नहीं'],color:'#FFD700'},
                {num:'02',title:'Copper Pyramid (Tamba) – Earth Element & Grounding',titleHi:'कॉपर पिरेमिड (ताम्बा) – पृथ्वी तत्व एवं स्थिरता',desc:'Copper is an excellent electrical conductor. Copper pyramids placed at dosha points absorb and redirect negative earth energies, creating a Faraday‑type protective field. Best in SW for stability, SE for fire activation, under bed for deep sleep.',descHi:'ताम्बा विद्युत का उत्तम चालक है। दोष बिंदुओं पर रखे गए ताम्बे के पिरामिड नकारात्मक भू-ऊर्जाओं को अवशोषित कर दिशा बदल देते हैं और फैराडे-प्रकार का सुरक्षात्मक क्षेत्र बनाते हैं। स्थिरता हेतु नैर्ऋत्य में सर्वोत्तम, अग्नि जागरण हेतु आग्नेय में, गहरी नींद हेतु बिस्तर के नीचे।',features:['Electrical conductor – earth grounding','SW zone for stability & relationships','Under‑bed placement for sleep','Geopathic stress neutralisation','Faraday‑type protective field'],featuresHi:['विद्युत चालक – पृथ्वी से जोड़ाव','स्थिरता एवं रिश्तों हेतु नैर्ऋत्य क्षेत्र','नींद हेतु बिस्तर के नीचे स्थापना','भू-रोगी तनाव का निवारण','फैराडे-प्रकार सुरक्षा क्षेत्र'],color:'#C88A5D'},
                {num:'03',title:'Brass Pyramid (Peetal) – Space Element & Financial Activation',titleHi:'पीतल पिरेमिड (प्रीतल) – आकाश तत्व एवं आर्थिक जागरण',desc:'Brass pyramids amplify the space (Akash) element, governing prosperity and expansion. Placed in North (Kuber zone) for wealth, NW for communication, above cash counter for commercial spaces.',descHi:'पीतल के पिरामिड आकाश तत्व को वर्धित करते हैं, जो समृद्धि एवं विस्तार के स्वामी हैं। धन हेतु उत्तर दिशा (कुबेर क्षेत्र) में, संचार हेतु उत्तर-पश्चिम में, तथा व्यावसायिक स्थानों में कैश काउंटर के ऊपर स्थापित करें।',features:['Akash (space) element amplification','North zone for wealth & career','NW zone for communication','Above cash counters in offices','Amplification hub for copper arrays'],featuresHi:['आकाश तत्व का वर्धन','धन एवं करियर हेतु उत्तर क्षेत्र','संचार हेतु उत्तर-पश्चिम क्षेत्र','कार्यालयों में कैश काउंटर के ऊपर','ताम्बे की सरणियों हेतु वर्धन केंद्र'],color:'#10B981'},
                {num:'04',title:'Crystal Pyramid (Sphatik) – Emotional Balance & NE Activation',titleHi:'क्रिस्टल पिरेमिड (स्फटिक) – भावनात्मक संतुलन एवं ईशान जागरण',desc:'Crystal pyramids activate the Northeast (Ishanya) — the most sacred zone governed by Jupiter and water element. Enhances spiritual connection, clarity, emotional equilibrium. Recommended for meditation rooms and study areas.',descHi:'स्फटिक के पिरामिड उत्तर-पूर्व (ईशान) को सक्रिय करते हैं — गुरु एवं जल तत्व से शासित सर्वाधिक पवित्र क्षेत्र। आध्यात्मिक जुड़ाव, स्पष्टता एवं भावनात्मक संतुलन को बढ़ाते हैं। ध्यान कक्षों एवं अध्ययन स्थलों हेतु अनुशंसित।',features:['NE (Ishanya) zone spiritual activation','Jupiter + water element alignment','Emotional equilibrium & clarity','Children\'s study & creativity zones','Harmonising complement to copper arrays'],featuresHi:['ईशान (उत्तर-पूर्व) क्षेत्र का आध्यात्मिक जागरण','गुरु + जल तत्व का संरेखण','भावनात्मक संतुलन एवं मानसिक स्पष्टता','बच्चों के अध्ययन एवं रचनात्मक क्षेत्र','ताम्बे की सरणियों का उत्तम पूरक'],color:'#8B5CF6'},
                {num:'05',title:'Parad (Mercury) Pyramid – Most Potent Dosha Neutraliser',titleHi:'पारद (मरकरी) पिरेमिड – सर्वाधिक प्रबल दोष निवारक',desc:'Solidified liquid mercury — the most powerful Vastu dosha neutraliser. Parad pyramids balance and harmonise the aura, abolishing negative energy from severe defects. Used for NE toilets, under‑staircases, illness‑prone spaces.',descHi:'ठोस किया गया द्रव पारद — सबसे शक्तिशाली वास्तु दोष निवारक। पारद के पिरामिड आभा को संतुलित एवं सौहार्दपूर्ण बनाते हैं और गंभीर दोषों की नकारात्मक ऊर्जा का नाश करते हैं। ईशान शौचालयों, सीढ़ियों के नीचे एवं रोग-प्रवण स्थानों हेतु प्रयुक्त।',features:['Solidified mercury – most potent remedy','Severe defect neutralisation (NE toilet)','Aura harmonisation & negativity abolition','Mantra‑energised before placement','For spaces with illness/financial distress'],featuresHi:['ठोस पारद – सर्वाधिक प्रबल उपचार','गंभीर दोष निवारण (ईशान शौचालय)','आभा सौहार्द एवं नकारात्मकता का नाश','स्थापना से पूर्व मंत्र-संजीवित','रोग एवं आर्थिक संकट वाले स्थानों हेतु'],color:'#C0C0C0'},
                {num:'06',title:'Bedroom & Sleep‑Zone Pyramid Placement Protocol',titleHi:'शयनकक्ष एवं नींद क्षेत्र पिरामिड स्थापना प्रोटोकॉल',desc:'Copper pyramid under mattress aligned to magnetic north improves sleep quality, reduces anxiety, neutralises geopathic stress below the bed. Crystal pyramid on bedside calms mind. Dual pyramids for couples balance.',descHi:'चुंबकीय उत्तर दिशा की ओर संरेखित गद्दे के नीचे का ताम्बे का पिरामिड नींद की गुणवत्ता सुधारता है, चिंता घटाता है और बिस्तर के नीचे के भू-रोगी तनाव को निष्प्रभावी करता है। शयन-मेज़ पर स्फटिक पिरामिड मन को शांत करता है। जोड़ों के संतुलन हेतु युग्म पिरामिड।',features:['Under‑mattress copper pyramid','Magnetic north alignment for sleep','Crystal on bedside for mental calm','Dual pyramids for relationship harmony','Children\'s NW brass pyramid for grounding'],featuresHi:['गद्दे के नीचे ताम्बे का पिरामिड','नींद हेतु चुंबकीय उत्तर संरेखण','मानसिक शांति हेतु शयन-मेज़ पर स्फटिक','रिश्तों के सामंजस्य हेतु युग्म पिरामिड','बच्चों हेतु उत्तर-पश्चिम में पीतल पिरामिड'],color:'#EC4899'},
                {num:'07',title:'Commercial & Workplace Pyramid Deployment',titleHi:'व्यावसायिक एवं कार्यस्थल पिरामिड विन्यास',desc:'Owner cabin: brass pyramid SW facing NE. Accounts: copper pyramid SE for fire element. Reception: crystal pyramid NE for first impressions. Dispatch: brass pyramid NW for swift movement. Measurable sales & profit increases reported.',descHi:'स्वामी केबिन: नैर्ऋत्य में पीतल का पिरामिड, मुख ईशान की ओर। खाता विभाग: आग्नेय में अग्नि तत्व हेतु ताम्बे का पिरामिड। रिसेप्शन: प्रभावशाली प्रथम छाप हेतु ईशान में स्फटिक पिरामिड। डिस्पैच: तीव्र गति हेतु उत्तर-पश्चिम में पीतल पिरामिड। बिक्री एवं लाभ में मापनीय वृद्धि दर्ज की गई।',features:['Owner cabin: brass pyramid SW→NE','Accounts: copper pyramid SE','Reception: crystal pyramid NE','Dispatch: brass pyramid NW','Measurable sales & profit increases'],featuresHi:['स्वामी केबिन: पीतल पिरामिड नैर्ऋत्य→ईशान','खाता विभाग: आग्नेय में ताम्बा पिरामिड','रिसेप्शन: ईशान में स्फटिक पिरामिड','डिस्पैच: उत्तर-पश्चिम में पीतल पिरामिड','बिक्री एवं लाभ में मापनीय वृद्धि'],color:'#FF9933'},
                {num:'08',title:'Pyramid Yantra Grid – Combined Pyramid + Sacred Geometry',titleHi:'पिरामिड-यंत्र ग्रिड – पिरामिड एवं पावन ज्यामिति का संयोजन',desc:'Copper pyramid above Vastu Purusha Yantra (alignment). Brass pyramid above Shri Yantra (wealth). Crystal pyramid above Navagraha Yantra (planetary balance). Multi‑dimensional energy correction at physical + metaphysical levels.',descHi:'वास्तु पुरुष यंत्र (संरेखण) के ऊपर ताम्बे का पिरामिड। श्री यंत्र (धन) के ऊपर पीतल का पिरामिड। नवग्रह यंत्र (ग्रह संतुलन) के ऊपर स्फटिक का पिरामिड। भौतिक एवं पारमार्थिक — दोनों स्तरों पर बहुआयामी ऊर्जा सुधार।',features:['Copper pyramid + Vastu Purusha Yantra','Brass pyramid + Shri Yantra for wealth','Crystal pyramid + Navagraha Yantra','Physical + metaphysical energy layers','Most comprehensive non‑structural remedy'],featuresHi:['ताम्बा पिरामिड + वास्तु पुरुष यंत्र','धन हेतु पीतल पिरामिड + श्री यंत्र','स्फटिक पिरामिड + नवग्रह यंत्र','भौतिक + पारमार्थिक ऊर्जा स्तर','सर्वांगपूर्ण गैर-संरचनात्मक उपचार'],color:'#6366F1'},
                {num:'09',title:'Pyramid Maintenance, Re‑Energisation & Annual Renewal',titleHi:'पिरामिड अनुरक्षण, पुनः-संजीवन एवं वार्षिक नवीनीकरण',desc:'Pyramids accumulate absorbed negative energy. Copper/brass: monthly salt‑water cleansing + 3‑4 hours sunlight discharge. Crystal: moonlight cleansing. Annual Vastu Shanti Havan re‑energisation. 6‑month pyramid rotation recommended.',descHi:'पिरामिड अवशोषित नकारात्मक ऊर्जा संचित करते हैं। ताम्बा/पीतल: मासिक नमक-जल से शुद्धि + 3–4 घंटे धूप में डिस्चार्ज। स्फटिक: चाँदनी से शुद्धि। वार्षिक वास्तु शांति हवन से पुनः-संजीवन। 6 माह में पिरामिड घूर्णन अनुशंसित।',features:['Monthly salt‑water cleansing for Cu/Brass','Sunlight discharge: 3‑4 hours','Crystal pyramid moonlight cleansing','Annual Vastu Shanti Havan re‑energisation','6‑month pyramid rotation recommended'],featuresHi:['ताम्बा/पीतल हेतु मासिक नमक-जल शुद्धि','धूप में डिस्चार्ज: 3–4 घंटे','स्फटिक पिरामिड की चाँदनी शुद्धि','वार्षिक वास्तु शांति हवन पुनः-संजीवन','6 माह में पिरामिड घूर्णन अनुशंसित'],color:'#F59E0B'},
              ].map((p,i)=>(
                <div key={i} className={`flex flex-col ${i%2===0?'lg:flex-row':'lg:flex-row-reverse'} gap-8 lg:gap-12 items-start`}>
                  <div className="lg:w-1/3 flex-shrink-0">
                    <div className="relative p-8 rounded-3xl bg-gradient-to-br from-[var(--color-bg-elevated)] via-[var(--color-bg-glass)] to-[var(--color-bg-glass)] backdrop-blur-md border border-prakash-gold/20 shadow-[0_10px_30px_rgba(0,0,0,0.06)] text-center">
                      <div className="absolute top-0 left-0 right-0 h-1.5 rounded-t-3xl" style={{backgroundColor:p.color}}/>
                      <div className="text-6xl font-bold mt-4 mb-2" style={{color:p.color}}>{p.num}</div>
                      <h3 className="font-serif text-xl text-nidra-indigo font-bold">{bi(p.title, p.titleHi).split('(')[0].trim()}</h3>
                      <p className="text-xs text-nidra-indigo/50 mt-1">{bi(p.title, p.titleHi).match(/\(.*?\)/)?.[0]?.replace(/[()]/g,'')}</p>
                    </div>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm sm:text-base text-nidra-indigo/70 leading-relaxed mb-4">{bi(p.desc, p.descHi)}</p>
                    <div className="flex flex-wrap gap-2">{p.features.map((f,j)=><span key={j} className="text-xs px-3 py-1.5 rounded-full border" style={{borderColor:p.color+'30',backgroundColor:p.color+'08',color:p.color}}>{bi(f, p.featuresHi?.[j])}</span>)}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── PYRAMID TYPES QUICK REFERENCE ── */}
        <section className="py-16 sm:py-24 bg-vastu-stone/10 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Quick Reference', 'झलक संदर्भ')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Pyramid Material Guide – Which Pyramid for Which Purpose?', 'पिरामिड सामग्री गाइड – किस उद्देश्य हेतु कौन सा पिरामिड?')}</h2></div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {[
                {material:'Copper Pyramid',materialHi:'कॉपर पिरामिड (ताम्बा)',element:'Earth (Prithvi)',elementHi:'पृथ्वी तत्व',uses:'Grounding, stability, geopathic stress neutralisation, under‑bed, SW corner, heavy machinery. EMF protection.',usesHi:'पृथ्वी से जोड़ाव, स्थिरता, भू-रोगी तनाव निवारण, बिस्तर के नीचे, नैर्ऋत्य कोण, भारी मशीनरी। EMF से सुरक्षा।',color:'#C88A5D'},
                {material:'Brass Pyramid',materialHi:'पीतल का पिरामिड',element:'Space (Akash)',elementHi:'आकाश तत्व',uses:'Wealth attraction, Kuber zone, cash counter, business premises, communication zones, NW placement.',usesHi:'धन आकर्षण, कुबेर क्षेत्र, कैश काउंटर, व्यावसायिक प्रतिष्ठान, संचार क्षेत्र, उत्तर-पश्चिम स्थापना।',color:'#FFD700'},
                {material:'Crystal Pyramid',materialHi:'स्फटिक का पिरामिड',element:'Water (Jal)',elementHi:'जल तत्व',uses:'Spiritual connection, emotional balance, NE zone, meditation room, children\'s study. Calming energies.',usesHi:'आध्यात्मिक जुड़ाव, भावनात्मक संतुलन, ईशान क्षेत्र, ध्यान कक्ष, बच्चों का अध्ययन। शांतकारी ऊर्जाएँ।',color:'#8B5CF6'},
                {material:'Parad Pyramid',materialHi:'पारद का पिरामिड',element:'All Elements',elementHi:'सभी तत्व',uses:'Most potent dosha neutraliser. Severe defects, illness‑prone spaces, financial distress, negative energy abolition.',usesHi:'सर्वाधिक प्रबल दोष निवारक। गंभीर दोष, रोग-प्रवण स्थान, आर्थिक संकट, नकारात्मक ऊर्जा का नाश।',color:'#C0C0C0'},
                {material:'9‑Pyramid Array',materialHi:'नौ-पिरामिड सरणी',element:'All 5 Elements',elementHi:'पाँचों तत्व',uses:'Whole‑house correction. Centre + 4 corners + 4 entrances. Complete dosha neutralisation. Permanent energy grid.',usesHi:'संपूर्ण गृह सुधार। केंद्र + चार कोण + चार प्रवेश द्वार। पूर्ण दोष निवारण। स्थायी ऊर्जा जाल।',color:'#FF9933'},
                {material:'Pyramid‑Yantra Grid',materialHi:'पिरामिड-यंत्र ग्रिड',element:'All + Metaphysical',elementHi:'सभी + पारमार्थिक',uses:'Copper + Vastu Purusha Yantra. Brass + Shri Yantra. Crystal + Navagraha Yantra. Multi‑dimensional correction.',usesHi:'ताम्बा + वास्तु पुरुष यंत्र। पीतल + श्री यंत्र। स्फटिक + नवग्रह यंत्र। बहुआयामी सुधार।',color:'#6366F1'},
              ].map((item,idx)=>(<div key={idx} className="bg-[var(--color-bg-glass)] backdrop-blur-sm rounded-2xl p-5 border border-prakash-gold/15 hover:shadow-lg"><div className="w-2 h-2 rounded-full mb-3" style={{backgroundColor:item.color}}/><h3 className="font-serif text-lg text-nidra-indigo font-bold">{bi(item.material, item.materialHi)}</h3><p className="text-xs text-nidra-indigo/50 mt-1 mb-2"><strong>{bi('Element:', 'तत्व:')}</strong> {bi(item.element, item.elementHi)}</p><p className="text-xs text-nidra-indigo/60">{bi(item.uses, item.usesHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── DOCUMENTED BENEFITS ── */}
        <section className="py-16 sm:py-24 bg-[var(--color-bg-elevated)] relative overflow-hidden">
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Documented Benefits', 'दर्ज लाभ')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Clinically Observed Benefits of Pyramid Therapy', 'पिरामिड चिकित्सा के नैदानिक रूप से अवलोकित लाभ')}</h2></div>
            <div className="grid sm:grid-cols-2 gap-5">
              {[
                {benefit:'Improved Sleep Quality',benefitHi:'नींद की बेहतर गुणवत्ता',detail:'Copper pyramids under mattress neutralise geopathic stress. Pyramidal copper energy re‑balances energies promoting deep, peaceful sleep.',detailHi:'गद्दे के नीचे ताम्बे के पिरामिड भू-रोगी तनाव को निष्प्रभावी करते हैं। पिरेमिडाकार ताम्बा ऊर्जा ऊर्जाओं को पुनःसंतुलित कर गहरी, शांतिपूर्ण नींद दिलाती है।',color:'#10B981'},
                {benefit:'Reduced Anxiety & Mental Clarity',benefitHi:'चिंता में कमी एवं मानसिक स्पष्टता',detail:'Crystal pyramids in NE corner or meditation space create calming environment. Pyramid acts as cosmic antenna absorbing mental noise.',detailHi:'ईशान कोण या ध्यान स्थान में स्फटिक पिरामिड शांतिपूर्ण वातावरण रचते हैं। पिरामिड मानसिक शोर को सोखने वाले दिव्य एंटीना समान कार्य करता है।',color:'#8B5CF6'},
                {benefit:'Financial Flow & Opportunity',benefitHi:'आर्थिक प्रवाह एवं अवसर',detail:'Brass pyramids in North (Kuber zone) activate wealth energy. Documented across multiple commercial Vastu consultations.',detailHi:'उत्तर दिशा (कुबेर क्षेत्र) में पीतल के पिरामिड धन-ऊर्जा को सक्रिय करते हैं। अनेक व्यावसायिक वास्तु परामर्शों में यह दर्ज किया गया है।',color:'#FFD700'},
                {benefit:'Geopathic Stress Neutralisation',benefitHi:'भू-रोगी तनाव का निवारण',detail:'Copper pyramids and rods create Faraday‑type protective field. 92% of cancer patients in Dr. Nieper\'s study were geopathically stressed.',detailHi:'ताम्बे के पिरामिड एवं रॉड फैराडे-प्रकार का सुरक्षात्मक क्षेत्र बनाते हैं। डॉ. नीपर के अध्ययन में 92% कैंसर रोगी भू-रोगी तनाव से ग्रस्त पाए गए।',color:'#C10000'},
                {benefit:'Relationship Harmony',benefitHi:'रिश्तों में सामंजस्य',detail:'Dual copper pyramids on either side of bed align energy fields of both partners. SW brass pyramid stabilises earth element.',detailHi:'बिस्तर के दोनों ओर युग्म ताम्बे के पिरामिड दोनों साथियों के ऊर्जा क्षेत्रों को संरेखित करते हैं। नैर्ऋत्य में पीतल का पिरामिड पृथ्वी तत्व को स्थिर करता है।',color:'#EC4899'},
                {benefit:'Dosha Correction Without Demolition',benefitHi:'बिना तोड़-फोड़ दोष सुधार',detail:'Parad pyramid placed above NE toilet permanently neutralises dosha on energetic plane — without relocating or breaking walls.',detailHi:'ईशान शौचालय के ऊपर रखा गया पारद पिरामिड ऊर्जात्मक स्तर पर दोष को स्थायी रूप से निष्प्रभावी करता है — बिना स्थानांतरण किए, बिना दीवार तोड़े।',color:'#C88A5D'},
              ].map((item,idx)=>(<div key={idx} className="bg-[var(--color-bg-glass)] backdrop-blur-sm rounded-2xl p-5 border border-prakash-gold/15 hover:shadow-lg"><div className="w-2 h-2 rounded-full mb-3" style={{backgroundColor:item.color}}/><h3 className="font-serif text-lg text-nidra-indigo font-bold mb-2">{bi(item.benefit, item.benefitHi)}</h3><p className="text-xs text-nidra-indigo/60">{bi(item.detail, item.detailHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── FINAL CTA ── */}
        <section className="relative py-24 sm:py-32 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10">
            <div className="max-w-3xl mx-auto text-center">
              <div className="relative rounded-[40px] p-[2px] bg-gradient-to-br from-prakash-gold/30 via-white/10 to-amber-400/30 shadow-[0_25px_60px_rgba(0,0,0,0.4)]">
                <div className="rounded-[38px] bg-[var(--color-bg-glass)] backdrop-blur-2xl p-8 sm:p-12 md:p-16 border border-[var(--color-border-soft)] shadow-inner">
                  <h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-[var(--color-hero-fg)] mb-4">{bi('Let AstroVastu Expert K.K. Nagaich Design Your Pyramid Energy Grid', 'एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच से रचवाइए अपनी पिरामिड ऊर्जा ग्रिड')}</h2>
                  <p className="text-[var(--color-hero-fg)]/70 text-base sm:text-lg max-w-xl mx-auto mb-10">{bi('Book a private Pyramidology consultation — performed personally by a 4th‑generation Vastu Guru, MBA, Ex‑CEO with 20+ years of clinical practice and 2 Lakh+ clients worldwide.', 'पिरामिड विद्या का निजी परामर्श बुक करें — 4 पीढ़ियों के वास्तु गुरु, MBA, पूर्व सीईओ, 20+ वर्षों के नैदानिक अनुभव एवं विश्वभर में 2 लाख+ क्लाइंट्स वाले के. के. नागाइच द्वारा व्यक्तिगत रूप से संपन्न।')}</p>
                  <Link href="/bookings" className="inline-block px-10 py-5 bg-gradient-to-r from-amber-500 via-prakash-gold to-sacred-saffron text-nidra-indigo font-bold rounded-full shadow-[0_10px_40px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_50px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Schedule Your Pyramid Consultation →', 'अपना पिरामिड परामर्श बुक करें →')}</Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      
      <style>{`@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-15px)}}@keyframes heroLoop{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}`}</style>
    </>
  );
}
