'use client';
import Header from '@/features/shared/components/Header';
import { SoundController } from '@/features/shared/components/SoundController';
import Link from 'next/link';
import { useBi } from '@/lib/i18n/Bilingual';

export default function MercuryParadPage() {
  const bi = useBi();
  return (
    <>

        {/* ── LOOPING GRADIENT HERO ── */}
        <section className="relative min-h-[85vh] flex items-center justify-center overflow-hidden bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(192,192,192,0.10),transparent_60%)]" />
          <div className="absolute top-20 left-[8%] w-80 h-80 rounded-full bg-gradient-to-br from-white/5 to-transparent backdrop-blur-3xl border border-[var(--color-border-soft)] animate-[float_10s_ease-in-out_infinite]" />
          <div className="absolute bottom-10 right-[5%] w-64 h-64 rounded-full bg-gradient-to-tl from-prakash-gold/8 to-transparent backdrop-blur-2xl border border-[var(--color-border-soft)] animate-[float_12s_ease-in-out_infinite_reverse]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10 text-center mt-16">
            <span className="text-prakash-gold uppercase tracking-[0.3em] text-xs sm:text-sm mb-4 block font-semibold">{bi('Advance Treatments · उन्नत उपचार', 'उन्नत उपचार')}</span>
            <h1 className="font-serif text-4xl sm:text-5xl md:text-7xl lg:text-8xl text-[var(--color-hero-fg)] mb-6 leading-tight drop-shadow-2xl"><span className="bg-gradient-to-r from-silver-300 via-prakash-gold to-sacred-saffron bg-clip-text text-transparent">{bi('Mercury / Parad Therapy', 'पारद चिकित्सा (मरकरी थेरेपी)')}</span></h1>
            <p className="text-base sm:text-lg md:text-xl text-[var(--color-hero-fg)]/70 max-w-3xl mx-auto mb-4 px-4 leading-relaxed">{bi('Parad Shivling Sthapna · Parad Pyramid Placement · Parad Keel Installation · Parad Gutika & Bracelet · Siddh Parad Ashtasanskar · Parad Yantra Energization · Parad Dhatu Adhyay · Parad Kavach Strips · Parad Lakshmi‑Ganesh Idols', 'पारद शिवलिंग स्थापना · पारद पिरामिड स्थापना · पारद कील स्थापन · पारद गुटिका व कंठी · सिद्ध पारद अष्टसंस्कार · पारद यंत्र संजीवन · पारद धातु अध्येय · पारद कवच पट्टियाँ · पारद लक्ष्मी-गणेश मूर्तियाँ')}</p>
            <p className="text-sm sm:text-base text-[var(--color-hero-fg)]/50 max-w-2xl mx-auto mb-10">{bi('9 sacred Parad (Mercury) practices — performed by AstroVastu Expert K.K. Nagaich, 4th generation Guru, MBA, Ex‑CEO. Parad, revered as the seed of Lord Shiva, is the most potent and auspicious metal in Vedic spiritual science.', 'नौ पावन पारद उपाय — एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा — 4 पीढ़ियों के गुरु, MBA, पूर्व सीईओ। शिव बीज रूप में पूज्य पारद, वैदिक आध्यात्मिक विज्ञान का सर्वाधिक प्रबल एवं मंगलमय धातु है।')}</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/bookings" className="px-10 py-5 bg-gradient-to-r from-silver-500 via-prakash-gold to-sacred-saffron text-nidra-indigo font-bold rounded-full shadow-[0_10px_30px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_45px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Book Parad Consultation', 'पारद परामर्श बुक करें')}</Link><Link href="#practices" className="bg-transparent border-2 border-white text-white hover:bg-white/10 px-10 py-5 rounded-full text-lg font-medium">{bi('Explore Practices ↓', 'उपाय जानें ↓')}</Link></div>
          </div>
        </section>

        {/* ── PARAD SCIENCE ── */}
        <section className="py-16 sm:py-24 bg-gradient-to-b from-[var(--color-bg-elevated)] via-vastu-stone/10 to-[var(--color-bg-elevated)] relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('The Seed of Lord Shiva', 'शिव बीज')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Parad – The Most Potent & Auspicious Metal in Vedic Spiritual Science', 'पारद – वैदिक आध्यात्मिक विज्ञान की सर्वाधिक प्रबल एवं मंगलमय धातु')}</h2><p className="text-nidra-indigo/60 max-w-3xl mx-auto text-sm">{bi('Parad (Mercury), purified through the 8‑stage Ashtasanskar of the Parad Samhita, neutralises severe Vastu doshas, attracts prosperity, protects against negative energies, and awakens Kundalini Shakti. The Brahma Purana states worshipping a Parad Shivling grants all worldly pleasures and Moksha.', 'पारद सम्हिता के अष्टसंस्कार — आठ-चरणीय शुद्धिकरण — से पवित्र किया गया पारद गंभीर वास्तु दोषों को निष्प्रभावी करता है, समृद्धि आकर्षित करता है, नकारात्मक शक्तियों से रक्षा करता है तथा कुंडलिनी शक्ति को जाग्रत करता है। ब्रह्म पुराण में कहा गया है कि पारद शिवलिंग की पूजा सभी भौतिक भोग और मोक्ष प्रदान करती है।')}</p></div>
          </div>
        </section>

        {/* ── 9 SACRED PRACTICES ── */}
        <section id="practices" className="py-16 sm:py-24 bg-[var(--color-bg-elevated)] relative">
          <div className="container mx-auto px-4 sm:px-6 max-w-6xl">
            <div className="text-center mb-14"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Nine Sacred Parad Practices', 'नौ पावन पारद उपाय')}</span><h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-nidra-indigo mt-3 mb-4">{bi('Complete Mercury Therapy Protocol', 'संपूर्ण पारद चिकित्सा विधि')}</h2><p className="text-nidra-indigo/60 max-w-2xl mx-auto text-sm">{bi('Rooted in the Brahma Purana, Shiva Purana, Parad Samhita, and Ras Ratna Samuccaya.', 'ब्रह्म पुराण, शिव पुराण, पारद संहिता तथा रस रत्नाकर संग्रह पर आधारित।')}</p></div>
            <div className="space-y-16">
              {[
                {num:'01',title:'Parad Shivling Sthapna (Mercury Shivling Installation in Northeast)',titleHi:'पारद शिवलिंग स्थापना (ईशान दिशा में)',desc:'The Parad Shivling, made from purified and solidified mercury through the Ashtasanskar, emits strong spiritual vibrations that purify the entire space. Installed in NE (Ishanya). Daily Rudra Abhishek. Equivalent to worshipping 108 stone Shivlings.',descHi:'अष्टसंस्कार द्वारा पवित्र एवं ठोस किए गए पारद से निर्मित पारद शिवलिंग प्रबल आध्यात्मिक कंपन उत्पन्न करता है, जो संपूर्ण स्थान को शुद्ध करता है। ईशान (उत्तर-पूर्व) में स्थापित। प्रतिदिन रुद्राभिषेक। 108 पाषाण शिवलिंगों की पूजा के तुल्य।',features:['Northeast (Ishanya) installation','Daily Rudra Abhishek','Ghee lamp at sunrise & sunset','Equivalent to 108 stone Shivlings','Attracts prosperity, clears negativity'],featuresHi:['ईशान (उत्तर-पूर्व) दिशा में स्थापना','प्रतिदिन रुद्राभिषेक','सूर्योदय व सूर्यास्त पर घी का दीप','108 पाषाण शिवलिंगों के तुल्य','समृद्धि आकर्षित करता है, नकारात्मकता दूर करता है'],color:'#C0C0C0'},
                {num:'02',title:'Parad Pyramid Placement (Energy Harmonization & Aura Balancing)',titleHi:'पारद पिरामिड स्थापना (ऊर्जा-सौहार्द व आभा संतुलन)',desc:'The Parad Pyramid balances and harmonises the aura. Four corners represent truth, peacefulness, wisdom, seriousness. Pointed apex signifies tri‑level divine power. Placed in any dosha zone, it neutralises negative energy permanently. Best at office desk or study table.',descHi:'पारद का पिरामिड आभा को संतुलित एवं सौहार्दपूर्ण बनाता है। इसके चार कोण सत्य, शांति, ज्ञान एवं गंभीरता के प्रतीक हैं। नोकदार शिखर त्रि-स्तरीय दिव्य शक्ति का सूचक है। किसी भी दोष क्षेत्र में रखने पर यह नकारात्मक ऊर्जा को स्थायी रूप से निष्प्रभावी करता है। कार्यालय मेज़ या अध्ययन-तालिका पर सर्वोत्तम।',features:['4 corners: Truth, Peace, Wisdom','Pointed apex: tri‑level divine power','Best at office/study desk','Between W‑SW for academic excellence','Balances & harmonises aura permanently'],featuresHi:['चार कोण: सत्य, शांति, ज्ञान','नोकदार शिखर: त्रि-स्तरीय दिव्य शक्ति','कार्यालय/अध्ययन मेज़ पर सर्वोत्तम','शैक्षणिक उत्कृष्टता हेतु पश्चिम–नैर्ऋत्य के मध्य','आभा को स्थायी रूप से संतुलित व सौहार्दपूर्ण बनाता है'],color:'#B8860B'},
                {num:'03',title:'Parad Keel Installation (Mercury Protection Spikes at Entry Points)',titleHi:'पारद कील स्थापन (प्रवेश द्वारों पर सुरक्षा कीलें)',desc:'Parad Keel (Mercury Spike), approximately 1.5 inches, 15‑20 grams. Embedded at entry points creating a protective shield blocking negative energies. Placed at four foundation corners to correct Vastu defects and balance energy flow. Attracts prosperity, promotes peace and harmony.',descHi:'पारद कील — लगभग 1.5 इंच, 15–20 ग्राम। प्रवेश द्वारों पर प्रोत करके सुरक्षा कवच रचती है जो नकारात्मक ऊर्जाओं को रोक देती है। आधार के चारों कोनों में वास्तु दोष सुधार एवं ऊर्जा-प्रवाह संतुलन हेतु स्थापित। समृद्धि आकर्षित करती है, शांति एवं सामंजस्य को बढ़ावा देती है।',features:['Embedded at main entrance threshold','4 foundation corners','Blocks negative energies, evil eye','Stabilises energetic foundation','Attracts prosperity & peace'],featuresHi:['मुख्य द्वार की दहलीज पर प्रोत','आधार के चारों कोण','नकारात्मक ऊर्जा व नजर को रोकती है','ऊर्जात्मक आधार को स्थिर करती है','समृद्धि एवं शांति आकर्षित करती है'],color:'#A9A9A9'},
                {num:'04',title:'Parad Gutika and Bracelet (Personal Spiritual Protection)',titleHi:'पारद गुटिका एवं कंठी (व्यक्तिगत आध्यात्मिक सुरक्षा)',desc:'Prepared with 8 Samskaras from the Parad Samhita, works directly on Sahasrara Chakra. Strengthens willpower, enhances concentration. Affects pineal gland, assists Kundalini awakening and deepens meditation. Available as single Gutika, bracelet, or 108+1 Mala.',descHi:'पारद संहिता के आठ संस्कारों से निर्मित, सीधे सहस्रार चक्र पर कार्य करती है। इच्छाशक्ति को बल देती है, एकाग्रेता बढ़ाती है। पिनियल ग्रंथि पर प्रभाव डालती है, कुंडलिनी जागरण में सहायक होती है एवं ध्यान को गहन बनाती है। एकल गुटिका, कंठी या 108+1 माला के रूप में उपलब्ध।',features:['Works on Sahasrara (Crown) Chakra','Enhances willpower, concentration','Assists Kundalini awakening','Gutika, bracelet, or 108+1 Mala','Removes fears & negative thought patterns'],featuresHi:['सहस्रार चक्र पर सीधा कार्य','इच्छाशक्ति व एकाग्रेता में वृद्धि','कुंडलिनी जागरण में सहायक','गुटिका, कंठी या 108+1 माला','भय व नकारात्मक विचार-प्रवृत्तियों का नाश'],color:'#708090'},
                {num:'05',title:'Siddh Parad Ashtasanskar (8‑Stage Purification from Parad Samhita)',titleHi:'सिद्ध पारद अष्टसंस्कार (पारद संहिता से आठ-चरणीय शुद्धि)',desc:'Raw mercury possesses 8 impurities (Doshas) and 7 external coverings. The Parad Samhita prescribes 18 processes, of which the first 8 constitute Ashtasanskar: Svedana, Mardana, Murchana, Utthapana, Patana, Bodhana, Niyamana, Deepana. Only mercury undergoing all 8 stages becomes Siddh Parad.',descHi:'कच्चे पारद में आठ दोष और सात बाहरी आवरण होते हैं। पारद संहिता में अठारह संस्कार वर्णित हैं, जिनमें प्रथम आठ अष्टसंस्कार हैं — स्वेदन, मर्दन, मुर्छन, उत्थापन, पातन, बोधन, नियामन एवं दीपन। आठों चरणों से गुजरा हुआ ही पारद सिद्ध पारद बनता है।',features:['Svedana: steam purification','Mardana: trituration with herb acids','Murchana: making Parad faint','Utthapana: directional energy elevation','Patana, Bodhana, Niyamana, Deepana'],featuresHi:['स्वेदन: भाप से शुद्धि','मर्दन: जड़ी-बूटी के रसों से मर्दन','मुर्छन: पारद को मुच्छित करना','उत्थापन: दिशात्मक ऊर्जा-उत्थान','पातन, बोधन, नियामन एवं दीपन'],color:'#808080'},
                {num:'06',title:'Parad Yantra Energization (Shri Yantra & Vastu Yantra Activation)',titleHi:'पारद यंत्र संजीवन (श्री यंत्र एवं वास्तु यंत्र जागरण)',desc:'When a Yantra is crafted from Parad and energised through specific mantras, it generates powerful vibrations that purify the aura. Parad Shri Yantra (9 interlocking triangles) in NE attracts wealth, harmony, spiritual growth while neutralising vastu defects.',descHi:'जब यंत्र पारद से निर्मित कर विशिष्ट मंत्रों से संजीवित किया जाता है, तो वह प्रबल कंपन उत्पन्न करता है जो आभा को पवित्र करता है। ईशान में पारद श्री यंत्र (नौ अंतर्लिखित त्रिभुज) धन, सामंजस्य एवं आध्यात्मिक वृद्धि आकर्षित करता है और वास्तु दोषों को निष्प्रभावी करता है।',features:['Parad Shri Yantra: 9 triangles','Place in Northeast or Brahmasthan','Liquid mercury energisation','Neutralises Vastu & planetary doshas','Attracts wealth, harmony, spiritual growth'],featuresHi:['पारद श्री यंत्र: नौ त्रिभुज','ईशान या ब्रह्मस्थान में स्थापित','पारद-संजीवन विधि','वास्तु एवं ग्रह दोषों का निवारण','धन, सामंजस्य व आध्यात्मिक वृद्धि आकर्षित'],color:'#BDB76B'},
                {num:'07',title:'Parad Dhatu Adhyay (Foundation Metal Embedment with Mercury)',titleHi:'पारद धातु अध्येय (आधार में पारद सहित धातु-प्रोतन)',desc:'Vedic practice of embedding mercury alongside other metals (Panch Dhatu) into the foundation. Mercury represents Budh, governing communication and intellect. Creates permanent energetic correction at structural level. Recommended for new constructions and renovations.',descHi:'आधार में पारद को अन्य धातुओं (पंचधातु) के साथ प्रोतने की वैदिक विधि। पारद बुध का प्रतीक है, जो संचार एवं बौद्धिकता का कारक है। संरचनात्मक स्तर पर स्थायी ऊर्जात्मक सुधार रचता है। नवीन निर्माण एवं जीर्णोद्धार हेतु अनुशंसित।',features:['Mercury embedment with Panch Dhatu','Permanent structural correction','Governs communication, intellect','For new construction & renovation','Balances elemental energies from ground'],featuresHi:['पंचधातु के साथ पारद-प्रोतन','संरचनात्मक स्तर पर स्थायी सुधार','संचार व बौद्धिकता का कारक','नवीन निर्माण एवं जीर्णोद्धार हेतु','मिट्टी से तत्व-ऊर्जाओं को संतुलित करता है'],color:'#696969'},
                {num:'08',title:'Parad Kavach Strips (Boundary Wall Mercury Protection)',titleHi:'पारद कवच पट्टियाँ (परिधि दीवारों पर पारद सुरक्षा)',desc:'Thin mercury‑based protective elements embedded into boundary walls at four cardinal directions. Functions as energetic shield preventing negative external influences. Corrects energy disturbances from irregular plot shapes. Combined with copper strips for comprehensive protection.',descHi:'चारों मुख्य दिशाओं की परिधि दीवारों में प्रोत पारद-आधारित पतली सुरक्षा पट्टियाँ। ऊर्जात्मक ढाल समान कार्य करके बाहरी नकारात्मक प्रभावों को रोकती हैं। अनियमित प्लॉट आकार से उत्पन्न ऊर्जा-विकृतियों को सुधारती हैं। सर्वांगीण सुरक्षा हेतु ताम्बे की पट्टियों के साथ संयुक्त।',features:['4 cardinal boundary wall points','Protective energetic shield','Prevents negative external influences','Combined with copper strips','Corrects irregular plot disturbances'],featuresHi:['परिधि दीवार के चार मुख्य दिशा-बिंदु','सुरक्षात्मक ऊर्जा ढाल','बाहरी नकारात्मक प्रभावों से रक्षा','ताम्बे की पट्टियों के साथ संयुक्त','अनियमित प्लॉट की ऊर्जा-विकृतियों का सुधार'],color:'#778899'},
                {num:'09',title:'Parad Lakshmi‑Ganesh Idols (Prosperity & Obstacle Removal)',titleHi:'पारद लक्ष्मी-गणेश मूर्तियाँ (समृद्धि व विघ्न निवारण)',desc:'Siddh Parad Lakshmi and Ganesh idols, crafted from purified mercury, are among the most auspicious sacred objects. Installed in NE direction, they attract prosperity, remove obstacles, and provide protection. Energised through Pran Pratishtha ritual. Daily worship with ghee lamp and incense.',descHi:'पवित्र पारद से निर्मित सिद्ध पारद की लक्ष्मी एवं गणेश मूर्तियाँ सर्वाधिक मंगलमय पावन वस्तुओं में गिनी जाती हैं। ईशान दिशा में स्थापित ये समृद्धि आकर्षित करती हैं, विघ्नों को दूर करती हैं तथा सुरक्षा प्रदान करती हैं। प्राण-प्रतिष्ठा अनुष्ठान से संजीवित। प्रतिदिन घी के दीप एवं धूप से पूजा।',features:['Northeast installation','Pran Pratishtha energisation','Attracts prosperity, removes obstacles','Protection from negative energies','Daily worship with ghee lamp & incense'],featuresHi:['ईशान दिशा में स्थापना','प्राण-प्रतिष्ठा से संजीवन','समृद्धि आकर्षित, विघ्न निवारण','नकारात्मक ऊर्जाओं से रक्षा','घी के दीप व धूप से प्रतिदिन पूजा'],color:'#DAA520'},
              ].map((p,i)=>(
                <div key={i} className={`flex flex-col ${i%2===0?'lg:flex-row':'lg:flex-row-reverse'} gap-8 lg:gap-12 items-start`}>
                  <div className="lg:w-1/3 flex-shrink-0">
                    <div className="relative p-8 rounded-3xl bg-gradient-to-br from-[var(--color-bg-elevated)] via-[var(--color-bg-glass)] to-[var(--color-bg-glass)] backdrop-blur-md border border-prakash-gold/20 shadow-[0_10px_30px_rgba(0,0,0,0.06)] text-center">
                      <div className="absolute top-0 left-0 right-0 h-1.5 rounded-t-3xl" style={{backgroundColor:p.color}}/>
                      <div className="text-6xl font-bold mt-4 mb-2" style={{color:p.color}}>{p.num}</div>
                      <h3 className="font-serif text-xl text-nidra-indigo font-bold">{bi(p.title, p.titleHi).split('(')[0].trim()}</h3>
                      <p className="text-xs text-nidra-indigo/50 mt-1">{bi(p.title, p.titleHi).match(/\(.*?\)/)?.[0]?.replace(/[()]/g,'')}</p>
                    </div>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm sm:text-base text-nidra-indigo/70 leading-relaxed mb-4">{bi(p.desc, p.descHi)}</p>
                    <div className="flex flex-wrap gap-2">{p.features.map((f,j)=><span key={j} className="text-xs px-3 py-1.5 rounded-full border" style={{borderColor:p.color+'30',backgroundColor:p.color+'08',color:p.color}}>{bi(f, p.featuresHi?.[j])}</span>)}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── SCRIPTURAL REFERENCE ── */}
        <section className="py-16 sm:py-24 bg-vastu-stone/10 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Scriptural Foundation', 'शास्त्रीय आधार')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Scriptural Foundation of Parad Therapy', 'पारद चिकित्सा का शास्त्रीय आधार')}</h2></div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
              {[
                {text:'Brahma Purana',textHi:'ब्रह्म पुराण',desc:'Worshipping a Parad Shivling grants all worldly pleasures and Moksha.',descHi:'पारद शिवलिंग की पूजा सभी भौतिक भोग एवं मोक्ष प्रदान करती है।'},
                {text:'Shiva Purana',textHi:'शिव पुराण',desc:'Parad Shivling equals 108 stone Shivlings; Lakshmi, Shiva, and Kuber reside where it is worshipped.',descHi:'पारद शिवलिंग 108 पाषाण शिवलिंगों के तुल्य है; जहाँ इसकी पूजा होती है, वहाँ लक्ष्मी, शिव एवं कुबेर निवास करते हैं।'},
                {text:'Parad Samhita',textHi:'पारद संहिता',desc:'Prescribes Ashtasanskar — the 8‑stage purification transforming raw mercury into Siddh Parad.',descHi:'अष्टसंस्कार का विधान — आठ-चरणीय शुद्धिकरण, जो कच्चे पारद को सिद्ध पारद में रूपांतरित करता है।'},
                {text:'Ras Ratna Samuccaya',textHi:'रस रत्नाकर संग्रह',desc:'Confirms properly prepared Parad as the most auspicious, capable of transmuting metals and healing diseases.',descHi:'यथार्थ रूप से निर्मित पारद को सर्वाधिक मंगलमय माना गया है — जो धातुओं में रूपांतरण एवं रोगों के उपचार में समर्थ है।'},
              ].map((s,i)=>(<div key={i} className="p-5 bg-[var(--color-bg-glass)] rounded-2xl border border-prakash-gold/15 text-center"><h3 className="font-serif text-lg text-nidra-indigo font-bold mb-2">{bi(s.text, s.textHi)}</h3><p className="text-xs text-nidra-indigo/60">{bi(s.desc, s.descHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── FINAL CTA ── */}
        <section className="relative py-24 sm:py-32 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10">
            <div className="max-w-3xl mx-auto text-center">
              <div className="relative rounded-[40px] p-[2px] bg-gradient-to-br from-silver-400/30 via-white/10 to-prakash-gold/30 shadow-[0_25px_60px_rgba(0,0,0,0.4)]">
                <div className="rounded-[38px] bg-[var(--color-bg-glass)] backdrop-blur-2xl p-8 sm:p-12 md:p-16 border border-[var(--color-border-soft)] shadow-inner">
                  <h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-[var(--color-hero-fg)] mb-4">{bi('Experience the Power of Parad', 'पारद की शक्ति का अनुभव करें')}</h2>
                  <p className="text-[var(--color-hero-fg)]/70 text-base sm:text-lg max-w-xl mx-auto mb-10">{bi('Book a consultation with AstroVastu Expert K.K. Nagaich for a personalised Parad prescription and sacred installation — performed personally by a 4th‑generation Vastu Guru with 20+ years of clinical practice and 2 Lakh+ clients worldwide.', 'एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच से व्यक्तिगत पारद-नुस्खे एवं पावन स्थापना हेतु परामर्श बुक करें — 4 पीढ़ियों के वास्तु गुरु, 20+ वर्षों के नैदानिक अनुभव एवं विश्वभर में 2 लाख+ क्लाइंट्स वाले के. के. नागाइच द्वारा व्यक्तिगत रूप से संपन्न।')}</p>
                  <Link href="/bookings" className="inline-block px-10 py-5 bg-gradient-to-r from-silver-500 via-prakash-gold to-sacred-saffron text-white font-bold rounded-full shadow-[0_10px_40px_rgba(192,192,192,0.3)] hover:shadow-[0_20px_50px_rgba(218,165,32,0.5)] transition-all text-lg">{bi('Book Your Parad Consultation', 'अपना पारद परामर्श बुक करें')}</Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      
      <style>{`@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-15px)}}@keyframes heroLoop{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}`}</style>
    </>
  );
}
