'use client';
import Header from '@/features/shared/components/Header';
import { SoundController } from '@/features/shared/components/SoundController';
import Link from 'next/link';
import { useBi } from '@/lib/i18n/Bilingual';

export default function GeopathicStressPage() {
  const bi = useBi();
  return (
    <>

        {/* ── LOOPING GRADIENT HERO ── */}
        <section className="relative min-h-[85vh] flex items-center justify-center overflow-hidden bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,80,80,0.08),transparent_60%)]" />
          <div className="absolute top-20 left-[8%] w-80 h-80 rounded-full bg-gradient-to-br from-prakash-gold/6 to-transparent backdrop-blur-3xl border border-[var(--color-border-soft)] animate-[float_10s_ease-in-out_infinite]" />
          <div className="absolute bottom-10 right-[5%] w-64 h-64 rounded-full bg-gradient-to-tl from-red-400/5 to-transparent backdrop-blur-2xl border border-[var(--color-border-soft)] animate-[float_12s_ease-in-out_infinite_reverse]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10 text-center mt-16">
            <span className="text-prakash-gold uppercase tracking-[0.3em] text-xs sm:text-sm mb-4 block font-semibold">{bi('Advance Treatments', 'उन्नत उपचार')}</span>
            <h1 className="font-serif text-4xl sm:text-5xl md:text-7xl lg:text-8xl text-[var(--color-hero-fg)] mb-6 leading-tight drop-shadow-2xl"><span className="bg-gradient-to-r from-red-400 via-prakash-gold to-sacred-saffron bg-clip-text text-transparent">{bi('Geopathic Stress', 'भू-रोगजनक तनाव')}</span></h1>
            <p className="text-base sm:text-lg md:text-xl text-[var(--color-hero-fg)]/70 max-w-3xl mx-auto mb-4 px-4 leading-relaxed">{bi('Geology · EMF & Geomagnetic Scanning · Copper Rod Installation · Pyramid & Crystal Therapy · Furniture Relocation · Plant‑Based Purification · Radon Detection · Hartmann & Curry Grid Mapping', 'भूविज्ञान · EMF एवं भूचुंबकीय स्कैनिंग · तांबे की छड़ स्थापना · पिरामिड एवं क्रिस्टल थेरेपी · फर्नीचर स्थानांतरण · पौधा-आधारित शुद्धि · रेडॉन पहचान · हार्टमैन एवं करी ग्रिड मैपिंग')}</p>
            <p className="text-sm sm:text-base text-[var(--color-hero-fg)]/50 max-w-2xl mx-auto mb-10">{bi('9 sacred geopathic stress practices — performed by AstroVastu Expert K.K. Nagaich, 4th generation Guru, MBA, Ex‑CEO — for homes, offices, factories & institutions.', '9 पवित्र भू-रोगजनक तनाव प्रथाएँ — एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा स्वयं संपन्न, 4थी पीढ़ी के गुरु, MBA, पूर्व सीईओ — घरों, कार्यालयों, कारखानों एवं संस्थानों हेतु।')}</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/bookings" className="px-10 py-5 bg-gradient-to-r from-red-500 via-prakash-gold to-sacred-saffron text-white font-bold rounded-full shadow-[0_10px_30px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_45px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Book Geopathic Audit', 'भू-रोग ऑडिट बुक करें')}</Link><Link href="#practices" className="bg-transparent border-2 border-white text-white hover:bg-white/10 px-10 py-5 rounded-full text-lg font-medium">{bi('Explore Practices ↓', 'प्रथाएँ जानें ↓')}</Link></div>
          </div>
        </section>

        {/* ── HARTMANN & CURRY GRIDS ── */}
        <section className="py-16 sm:py-24 bg-gradient-to-b from-[var(--color-bg-elevated)] via-vastu-stone/10 to-[var(--color-bg-elevated)] relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('The Invisible Blueprint of Suffering', 'कष्टों का अदृश्य नक्शा')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('The Hartmann & Curry Grids — Earth\'s Geomagnetic Matrix', 'हार्टमैन एवं करी ग्रिड — पृथ्वी का भूचुंबकीय मैट्रिक्स')}</h2><p className="text-nidra-indigo/60 max-w-3xl mx-auto text-sm">{bi('Dr. Ernst Hartmann and Dr. Manfred Curry independently discovered intersecting grids of geomagnetic lines. Where Hartmann, Curry, and underground water veins intersect, a vortex of geopathic disturbance forms — the invisible zones where prolonged exposure weakens the immune system.', 'डॉ. एर्नस्ट हार्टमैन एवं डॉ. मैन्फ्रेड करी ने स्वतंत्र रूप से भूचुंबकीय रेखाओं के परस्पर-च्छेदी ग्रिड की खोज की। जहाँ हार्टमैन, करी एवं भूगर्भ जल-शिराएँ मिलती हैं, भू-रोगजनक विक्षोभ का भंवर बनता है — वे अदृश्य क्षेत्र जहाँ दीर्घकालिक प्रभाव से रोग-प्रतिरोध क्षीण होता है।')}</p></div>
          </div>
        </section>

        {/* ── 9 SACRED PRACTICES ── */}
        <section id="practices" className="py-16 sm:py-24 bg-[var(--color-bg-elevated)] relative">
          <div className="container mx-auto px-4 sm:px-6 max-w-6xl">
            <div className="text-center mb-14"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('The 9 Sacred Practices', '9 पवित्र प्रथाएँ')}</span><h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-nidra-indigo mt-3 mb-4">{bi('Authentic Vedic Practices for Geopathic Stress Detection & Neutralisation', 'भू-रोगजनक तनाव की पहचान एवं निष्क्रियीकरण हेतु प्रामाणिक वैदिक प्रथाएँ')}</h2><p className="text-nidra-indigo/60 max-w-2xl mx-auto text-sm">{bi('Each practice uses specialised instruments and traditional dowsing techniques refined by AstroVastu Expert K.K. Nagaich.', 'प्रत्येक प्रथा में विशेष उपकरण एवं एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा परिष्कृत पारंपरिक डाउसिंग तकनीकें प्रयुक्त होती हैं।')}</p></div>
            <div className="space-y-16">
              {[
                {num:'01',title:'The Vilsbiburg Protocol — Baron von Pohl\'s 1929 Cancer Mapping',titleHi:'विल्सबिबर्ग प्रोटोकॉल — बैरन वॉन पॉल का 1929 कैंसर मैपिंग',desc:'In 1929, von Pohl mapped geopathic stress lines in Vilsbiburg and found 100% correlation between cancer deaths and underground water vein crossings. Dr. Hans Nieper found 92% of cancer patients and 75% of MS patients were geopathically stressed. Over 85% of cancer deaths are linked to GS exposure.',descHi:'1929 में वॉन पॉल ने विल्सबिबर्ग में भू-रोगजनक तनाव रेखाएँ चित्रित कीं और कैंसर मृत्यु एवं भूगर्भ जल-शिराओं के चौराहे में 100% सहसंबंध पाया। डॉ. हॉन्स नीपर ने देखा कि 92% कैंसर रोगी एवं 75% MS रोगी भू-रोगजनक रूप से तनावग्रस्त थे। 85% से अधिक कैंसर मृत्यु GS संपर्क से जुड़ी हैं।',features:['1929 Vilsbiburg 100% cancer correlation','Dr. Nieper: 92% cancer, 75% MS GS+','Dr. Hartmann: cancer = location disease','85%+ cancer deaths linked to GS','200ft underground vein mapping'],featuresHi:['1929 विल्सबिबर्ग 100% कैंसर सहसंबंध','डॉ. नीपर: 92% कैंसर, 75% MS GS+','डॉ. हार्टमैन: कैंसर = स्थान-जन्य रोग','85%+ कैंसर मृत्यु GS से जुड़ी','200 फीट भूगर्भ शिरा मैपिंग'],color:'#C10000'},
                {num:'02',title:'Copper L‑Rod Dowsing (Geopathic Zone Detection & Mapping)',titleHi:'तांबे की L‑रॉड डाउसिंग (भू-रोग क्षेत्र पहचान एवं मैपिंग)',desc:'Dowsing with copper L‑rods remains the oldest and most reliable detection method. Rods cross involuntarily over underground water veins, fault lines, or grid intersections. Von Pohl scale (0‑16) quantifies intensity. AstroVastu Expert trained under three Guru‑Shishya lineages.',descHi:'तांबे की L‑रॉड से डाउसिंग प्राचीनतम एवं सर्वाधिक विश्वसनीय पहचान पद्धति है। भूगर्भ जल-शिराओं, भ्रंश रेखाओं या ग्रिड चौराहों पर रॉड अनैच्छिक रूप से क्रॉस होती हैं। वॉन पॉल स्केल (0–16) तीव्रता निर्धारित करता है। एस्ट्रोवास्तु एक्सपर्ट तीन गुरु-शिष्य परंपराओं में प्रशिक्षित।',features:['Copper L‑rod dowsing','Von Pohl scale 0‑16','Hartmann & Curry grid mapping','Underground water vein depth','Full property zone mapping'],featuresHi:['तांबे की L‑रॉड डाउसिंग','वॉन पॉल स्केल 0–16','हार्टमैन एवं करी ग्रिड मैपिंग','भूगर्भ जल-शिरा गहराई','संपूर्ण संपत्ति क्षेत्र मैपिंग'],color:'#E8B960'},
                {num:'03',title:'Gauss Meter & EMF Detection (Quantitative Measurement)',titleHi:'गॉस मीटर एवं EMF पहचान (मात्रात्मक मापन)',desc:'Normal background: 25‑65 µT. Geopathic stress zones: 100+ µT. Trifield TF2 multi‑spectrum EMF detection. Man‑made radiation from power lines, Wi‑Fi, mobile towers compounds natural GS — termed technopathic stress.',descHi:'सामान्य पृष्ठभूमि: 25–65 µT। भू-रोगजनक तनाव क्षेत्र: 100+ µT। ट्राइफील्ड TF2 मल्टी-स्पेक्ट्रम EMF पहचान। विद्युत लाइन, Wi‑Fi एवं मोबाइल टावर से मानव-निर्मित विकिरण प्राकृतिक GS को और बढ़ाता है — इसे टेक्नोपैथिक तनाव कहते हैं।',features:['Gauss meter: 25‑65 µT normal','100+ µT = GS zone','Trifield TF2 EMF detection','Technopathic stress identification','Wi‑Fi, tower & power line mapping'],featuresHi:['गॉस मीटर: सामान्य 25–65 µT','100+ µT = GS क्षेत्र','ट्राइफील्ड TF2 EMF पहचान','टेक्नोपैथिक तनाव पहचान','Wi‑Fi, टावर एवं विद्युत लाइन मैपिंग'],color:'#FF9933'},
                {num:'04',title:'Biomedical Validation — GDV Gas Discharge Visualization (2025)',titleHi:'जैव-चिकित्सीय प्रमाणिकरण — GDV गैस-निर्वेशन दृश्यीकरण (2025)',desc:'Randomised, double‑blinded trial with 52 persons. Statistically significant differences in physical area of glow between geopathic vs neutral zones. Deficits in lymphatic, cardiovascular, and pineal systems were documented. Peer‑reviewed biomedical journal publication.',descHi:'52 व्यक्तियों पर यादृच्छिक, द्वि-अंध परीक्षण। भू-रोगजनक एवं तटस्थ क्षेत्रों में चमक के भौतिक विस्तार में सांख्यिकीय सार्थक अंतर। लसीिका, हृदय-संवाही एवं पीनियल तंत्र की अप्रचाटता दर्ज की गई। समकक्ष-समीक्षित जैव-चिकित्सा जर्नल में प्रकाशित।',features:['52‑person double‑blinded trial','Statistically significant glow reduction','Lymphatic, cardiovascular, pineal deficits','Geowave harmonization demonstrated','Peer‑reviewed publication'],featuresHi:['52-व्यक्ति द्वि-अंध परीक्षण','चमक में सांख्यिकीय सार्थक ह्रास','लसीिका, हृदय-संवाही, पीनियल अप्रचाटता','जियोवेव हार्मोनाइजेशन सिद्ध','समकक्ष-समीक्षित प्रकाशन'],color:'#6366F1'},
                {num:'05',title:'Copper Rod Installation (Geopathic Stress Neutraliser)',titleHi:'तांबे की छड़ स्थापना (भू-रोगजनक तनाव निष्क्रियक)',desc:'18‑24 inch energised copper rods driven at stress‑line entry points. Faraday‑type effect redirects harmful radiation. South corner placement for intersecting veins. Mantra‑energised before installation. Multiple rods for large zones.',descHi:'तनाव-रेखा प्रवेश बिंदुओं पर 18–24 इंच ऊर्जावान तांबे की छड़ें ठोकी जाती हैं। फैराडे-प्रकार का प्रभाव हानिकारक विकिरण को विचलित करता है। चौराही शिराओं हेतु दक्षिण कोण स्थापना। स्थापना से पूर्व मंत्र-ऊर्जांकित। बड़े क्षेत्रों हेतु अनेक छड़ें।',features:['18‑24 inch energised copper rods','Faraday‑type radiation redirection','South corner & entry placement','Multiple rods for intersecting veins','Mantra‑energised installation'],featuresHi:['18–24 इंच ऊर्जावान तांबे की छड़ें','फैराडे-प्रकार विकिरण-विचलन','दक्षिण कोण एवं प्रवेश स्थापना','चौराही शिराओं हेतु अनेक छड़ें','मंत्र-ऊर्जांकित स्थापना'],color:'#10B981'},
                {num:'06',title:'Pyramid & Crystal Grid Therapy',titleHi:'पिरामिड एवं क्रिस्टल ग्रिड थेरेपी',desc:'Octagonal copper pyramids absorb geopathic forces from all 8 directions. Brass pyramids for financial zones. Crystal grids: black tourmaline (EMF absorption), amethyst (neurological calm), clear quartz (amplification), smoky quartz (detoxification).',descHi:'अष्टभुजाकार तांबे के पिरामिड सभी 8 दिशाओं से भू-रोगजनक बल अवशोषित करते हैं। आर्थिक क्षेत्र हेतु पीतल के पिरामिड। क्रिस्टल ग्रिड: ब्लैक टूरमलाइन (EMF अवशोषण), एमेथिस्ट (तंत्रिका-शांति), क्लियर क्वार्ट्ज़ (वर्धन), स्मोकी क्वार्ट्ज़ (विषाहरण)।',features:['Octagonal copper pyramid (8‑direction)','Brass pyramid for financial zones','Black tourmaline EMF absorption','Amethyst for neurological calming','Clear quartz + smoky quartz'],featuresHi:['अष्टभुजाकार तांबा पिरामिड (8-दिशा)','आर्थिक क्षेत्र हेतु पीतल पिरामिड','ब्लैक टूरमलाइन EMF अवशोषण','एमेथिस्ट तंत्रिका-शांति हेतु','क्लियर क्वार्ट्ज़ + स्मोकी क्वार्ट्ज़'],color:'#8B5CF6'},
                {num:'07',title:'Furniture Relocation & Sleep Zone Optimisation',titleHi:'फर्नीचर स्थानांतरण एवं नींद-क्षेत्र अनुकूलन',desc:'Move bed/work desk 3‑5 feet from mapped GS line. During sleep the brain sends regeneration signals — GS exposure during sleep is most damaging. Children instinctually avoid GS zones — odd sleep angles and refusal to sleep in room are key indicators.',descHi:'तय GS रेखा से बिस्तर/कार्य-मेज 3–5 फीट हटाएँ। नींद में मस्तिष्क पुनर्जनन संकेत भेजता है — नींद के दौरान GS संपर्क सर्वाधिक हानिकारक। बच्चे सहजतः GS क्षेत्र टालते हैं — विचित्र कोण पर सोना एवं कक्ष में सोने से इनकार प्रमुख संकेत।',features:['Bed relocation 3‑5 feet from GS','Work desk repositioning','Children\'s instinctive avoidance','Sleep‑walking as GS indicator','Immediate health improvement'],featuresHi:['GS से 3–5 फीट बिस्तर स्थानांतरण','कार्य-मेज पुनः-स्थापन','बच्चों की सहज परहेज','नींद-चाल GS संकेत','तत्काल स्वास्थ्य सुधार'],color:'#F59E0B'},
                {num:'08',title:'Plant‑Based Purification & Rock Salt Absorption',titleHi:'पौधा-आधारित शुद्धि एवं शिला-लवण अवशोषण',desc:'Snake plant (SE/S) purifies air. Areca palm (E/NE) reduces stress. Peace lily (E/N/NE) for emotional healing. Rock salt in glass bowls absorbs negative vibrations — replace every 10 days. Multiple Tulsi (basil) plants neutralise GS.',descHi:'स्नेक प्लांट (आग्नेय/दक्षिण) वायु शुद्ध करता है। एरेका पाम (पूर्व/ईशान) तनाव घटाता है। पीस लिली (पूर्व/उत्तर/ईशान) भावनात्मक उपचार हेतु। कांच के कटोरे में शिला-लवण नकारात्मक कंपन अवशोषित करता है — हर 10 दिन बदलें। अनेक तुलसी पौधे GS निष्क्रिय करते हैं।',features:['Snake plant SE/S for purification','Areca palm E/NE for stress','Peace lily E/N/NE for healing','Rock salt bowls – 10‑day cycle','Tulsi for natural GS neutralisation'],featuresHi:['शुद्धि हेतु स्नेक प्लांट आग्नेय/दक्षिण','तनाव हेतु एरेका पाम पूर्व/ईशान','उपचार हेतु पीस लिली पूर्व/उत्तर/ईशान','शिला-लवण कटोरे – 10-दिन चक्र','प्राकृतिक GS निष्क्रियण हेतु तुलसी'],color:'#06B6D4'},
                {num:'09',title:'EMF Shielding & Technopathic Stress Reduction (Digital Sunset)',titleHi:'EMF शील्डिंग एवं टेक्नोपैथिक तनाव ह्रास (डिजिटल सनसेट)',desc:'EMF‑shielding bed canopies, curtains, paint. Switch off Wi‑Fi at night. Mobile phones 6 feet from beds. Digital sunset: all wireless devices off 60 minutes before sleep. Grounding mats and periodic Gauss meter reassessment.',descHi:'EMF-शील्डिंग बिस्तर-कॉनोपी, पर्दे, पेंट। रात्रि में Wi‑Fi बंद। बिस्तर से 6 फीट दूर मोबाइल फोन। डिजिटल सनसेट: सोने से 60 मिनट पूर्व सभी वायरलेस उपकरण बंद। ग्राउंडिंग मैट एवं अंतराल पर गॉस मीटर पुनर्मापन।',features:['EMF‑shielding bed canopy','Wi‑Fi off at night','Phone 6‑foot distance','Digital sunset: 60‑min pre‑sleep','Periodic Gauss reassessment'],featuresHi:['EMF-शील्डिंग बिस्तर कॉनोपी','रात्रि में Wi‑Fi बंद','फोन 6-फीट की दूरी','डिजिटल सनसेट: नींद से पूर्व 60 मिनट','अंतराल पर गॉस पुनर्मापन'],color:'#EF4444'},
              ].map((p,i)=>(
                <div key={i} className={`flex flex-col ${i%2===0?'lg:flex-row':'lg:flex-row-reverse'} gap-8 lg:gap-12 items-start`}>
                  <div className="lg:w-1/3 flex-shrink-0">
                    <div className="relative p-8 rounded-3xl bg-gradient-to-br from-[var(--color-bg-elevated)] via-[var(--color-bg-glass)] to-[var(--color-bg-glass)] backdrop-blur-md border border-prakash-gold/20 shadow-[0_10px_30px_rgba(0,0,0,0.06)] text-center">
                      <div className="absolute top-0 left-0 right-0 h-1.5 rounded-t-3xl" style={{backgroundColor:p.color}}/>
                      <div className="text-6xl font-bold mt-4 mb-2" style={{color:p.color}}>{p.num}</div>
                      <h3 className="font-serif text-xl text-nidra-indigo font-bold">{bi(p.title.split('(')[0].trim(), p.titleHi.split('(')[0].trim())}</h3>
                      <p className="text-xs text-nidra-indigo/50 mt-1">{bi(p.title.match(/\(.*?\)/)?.[0]?.replace(/[()]/g,'') ?? '', p.titleHi.match(/\(.*?\)/)?.[0]?.replace(/[()]/g,'') ?? '')}</p>
                    </div>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm sm:text-base text-nidra-indigo/70 leading-relaxed mb-4">{bi(p.desc, p.descHi)}</p>
                    <div className="flex flex-wrap gap-2">{p.features.map((f,j)=><span key={j} className="text-xs px-3 py-1.5 rounded-full border" style={{borderColor:p.color+'30',backgroundColor:p.color+'08',color:p.color}}>{bi(f, p.featuresHi?.[j])}</span>)}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── HEALTH SYMPTOMS CHECKLIST ── */}
        <section className="py-16 sm:py-24 bg-vastu-stone/10 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Health Reference', 'स्वास्थ्य संदर्भ')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Geopathic Stress Symptoms — What to Look For', 'भू-रोगजनक तनाव के लक्षण — किन संकेतों पर ध दें')}</h2></div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {[
                {category:'Sleep Disorders',categoryHi:'नींद संबंधी विकार',symptoms:'Insomnia, restless sleep, nightmares, waking 2‑3 AM, waking exhausted, bruxism, sleep‑walking.',symptomsHi:'अनिद्रा, बेचैन नींद, बुरे सपने, रात 2–3 बजे उठना, थकावट से उठना, दंत-मर्दन, नींद में चलना।',color:'#EF4444'},
                {category:'Chronic Fatigue',categoryHi:'दीर्नालस थकान',symptoms:'Constant tiredness, low energy, drowsiness, waking un‑refreshed. Adrenal gland overtime compensation.',symptomsHi:'निरंतर थकान, कम ऊर्जा, नींद-आवेश, ताज़ा न हो पाना। अधिवृक्क ग्रंथि की अति-क्षतिपूर्ति।',color:'#F59E0B'},
                {category:'Immune Dysfunction',categoryHi:'रोग-प्रतिरोध दोष',symptoms:'Frequent illnesses, slow recovery, repeated infections, auto‑immune flare‑ups, not responding to treatment.',symptomsHi:'बार-बार बीमारी, सुस्ति में विलंब, बार-बार संक्रमण, ऑटो-इम्यून प्रकोप, उपचार पर अनुत्तरदायित्व।',color:'#C10000'},
                {category:'Neurological',categoryHi:'तंत्रिका संबंधी',symptoms:'Brain fog, difficulty concentrating, memory loss, depression, anxiety, mood swings, aggression.',symptomsHi:'मस्तिष्क-मंदता, एकाग्रता में कठिनाई, स्मृति-हानि, अवसाद, चिंता, मिज़ाज-उतार-चढ़ाव, आक्रामकता।',color:'#8B5CF6'},
                {category:'Pain & Inflammation',categoryHi:'दर्द एवं सूजन',symptoms:'Persistent headaches, migraines, joint pains, arthritis, rheumatism, back problems.',symptomsHi:'निरंतर सिरदर्द, आधेशीर्षक (माइग्रेन), जोड़ों का दर्द, गठिया, वात-रोग, पीठ संबंधी समस्याएँ।',color:'#FF9933'},
                {category:'Children\'s Indicators',categoryHi:'बच्चों के संकेत',symptoms:'Refusing to sleep in room, sleep‑walking, waking at odd angles, tiredness, poor schoolwork, bed‑wetting.',symptomsHi:'कक्ष में सोने से इनकार, नींद में चलना, विचित्र कोण पर जागना, थकान, पढ़ाई में दुर्बलता, बिस्तर गीला करना।',color:'#06B6D4'},
                {category:'Reproductive',categoryHi:'प्रजनन संबंधी',symptoms:'Unexplained infertility, recurrent miscarriages, difficulty conceiving, menstrual irregularities, cot deaths.',symptomsHi:'अज्ञात बांझपन, बार-बार गर्भपात, गर्भधारण में कठिनाई, मासिक-धर्म अव्यवस्था, शिशु-मृत्यु।',color:'#EC4899'},
                {category:'Physical Indicators',categoryHi:'भौतिक संकेत',symptoms:'Cats sleeping in specific spots, ants/wasps/bees nests, twisted tree growth, gaps in hedges, lightning‑struck trees.',symptomsHi:'बिल्लियों का विशिष्ट स्थानों पर सोना, चींटी/ततई/मधुमक्खी के घोंसले, टेढ़े वृक्ष-विकास, बाड़ में अंतराल, बिजली-गिरा वृक्ष।',color:'#10B981'},
                {category:'Building Indicators',categoryHi:'भवन संकेत',symptoms:'Cracked plaster, damp patches, recurring mould, machinery breakdowns in specific zones, sick building syndrome.',symptomsHi:'टूटा प्लास्टर, नमी के क्षेत्र, बार-बार फफूंद, विशिष्ट क्षेत्रों में मशीन खराबी, सिक्स बिल्डिंग सिंड्रोम।',color:'#6366F1'},
              ].map((item,idx)=>(<div key={idx} className="bg-[var(--color-bg-glass)] backdrop-blur-sm rounded-2xl p-5 border border-prakash-gold/15 hover:shadow-lg"><div className="w-2 h-2 rounded-full mb-3" style={{backgroundColor:item.color}}/><h3 className="font-serif text-lg text-nidra-indigo font-bold">{bi(item.category, item.categoryHi)}</h3><p className="text-xs text-nidra-indigo/60 mt-1">{bi(item.symptoms, item.symptomsHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── DETECTION METHODS ── */}
        <section className="py-16 sm:py-24 bg-[var(--color-bg-elevated)] relative overflow-hidden">
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Detection Methods', 'पहचान विधियाँ')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('5 Proven Geopathic Stress Detection Methods', '5 सिद्ध भू-रोगजनक तनाव पहचान विधियाँ')}</h2></div>
            <div className="grid sm:grid-cols-2 gap-5">
              {[
                {method:'Copper L‑Rod Dowsing',methodHi:'तांबे की L‑रॉड डाउसिंग',detail:'The oldest and most reliable method. Two copper L‑shaped rods cross involuntarily over underground water veins and grid intersections. Von Pohl used this to map the Vilsbiburg cancer clusters.',detailHi:'सर्वाधिक प्राचीन एवं विश्वसनीय पद्धति। दो तांबे की L-आकार छड़ें भूगर्भ जल-शिराओं एवं ग्रिड चौराहों पर अनैच्छिक रूप से क्रॉस होती हैं। वॉन पॉल ने इसी से विल्सबिबर्ग के कैंसर-गुच्छ चित्रित किए।',color:'#E8B960'},
                {method:'Gauss Meter (Magnetometer)',methodHi:'गॉस मीटर (मैग्नीटोमीटर)',detail:'Measures local magnetic field strength in microtesla (µT). Normal: 25‑65 µT. GS zones: 100+ µT or sharp fluctuations. Provides quantitative validation of dowsing results.',detailHi:'माइक्रोटेस्ला (µT) में स्थानीय चुंबकीय क्षेत्र की तीव्रता मापता है। सामान्य: 25–65 µT। GS क्षेत्र: 100+ µT या तीव्र उतार-चढ़ाव। डाउसिंग परिणामों का मात्रात्मक प्रमाणिकरण देता है।',color:'#6366F1'},
                {method:'EMF Meter (Trifield TF2)',methodHi:'EMF मीटर (ट्राइफील्ड TF2)',detail:'Measures electromagnetic field radiation from man‑made sources. Combined with Gauss meter for complete picture of natural + man‑made radiation.',detailHi:'मानव-निर्मित स्रोतों से विद्युत-चुंबकीय क्षेत्र विकिरण मापता है। प्राकृतिक + मानव-निर्मित विकिरण के संपूर्ण चित्र हेतु गॉस मीटर से संयुक्त।',color:'#10B981'},
                {method:'Radon Detector',methodHi:'रेडॉन डिटेक्टर',detail:'Radon is the second leading cause of lung cancer globally (WHO). Geological fault lines and granite‑rich regions emit radon. Detectors placed 48‑72 hours.',detailHi:'रेडॉन विश्व में फेफड़ा-कैंसर का दूसरा प्रमुख कारण (WHO)। भूगर्भ भ्रंश रेखाएँ एवं ग्रेनाइट-समृद्ध क्षेत्र रेडॉन उत्सर्जित करते हैं। डिटेक्टर 48–72 घंटे रखे जाते हैं।',color:'#EF4444'},
                {method:'Thermal Imaging & Universal Scanner',methodHi:'थर्मल इमेजिंग एवं यूनिवर्सल स्कैनर',detail:'Detects temperature anomalies in walls and floors caused by underground water flow. Correlates with dowsing and magnetometer readings for visual confirmation.',detailHi:'भूगर्भ जल-प्रवाह से दीवारों एवं फर्श में तापमान-विसंगति पहचानता है। दृश्य पुष्टि हेतु डाउसिंग एवं मैग्नीटोमीटर पाठों से सहसंबंध।',color:'#8B5CF6'},
              ].map((item,idx)=>(<div key={idx} className="bg-[var(--color-bg-glass)] backdrop-blur-sm rounded-2xl p-5 border border-prakash-gold/15 hover:shadow-lg"><div className="w-2 h-2 rounded-full mb-3" style={{backgroundColor:item.color}}/><h3 className="font-serif text-lg text-nidra-indigo font-bold">{bi(item.method, item.methodHi)}</h3><p className="text-xs text-nidra-indigo/60 mt-1">{bi(item.detail, item.detailHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── REMEDIES WITHOUT DEMOLITION ── */}
        <section className="py-16 sm:py-24 bg-vastu-stone/10 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Non‑Invasive Corrections', 'बिना तोड़-फोड़ के सुधार')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Remedies Without Demolition — 7 Proven GS Correction Techniques', 'बिना तोड़-फोड़ के उपचार — 7 सिद्ध GS सुधार तकनीकें')}</h2></div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {[
                {title:'Copper Rod Installation',titleHi:'तांबे की छड़ स्थापना',desc:'18‑24 inch rods, mantra‑energised, driven at stress‑line entry points. Faraday‑type effect redirects radiation.',descHi:'18–24 इंच छड़ें, मंत्र-ऊर्जांकित, तनाव-रेखा प्रवेश बिंदुओं पर ठोकीं। फैराडे-प्रकार प्रभाव विकिरण विचलित करता है।',color:'#FFD700'},
                {title:'Pyramid Placement',titleHi:'पिरामिड स्थापना',desc:'Octagonal copper pyramids under beds/desks. Brass pyramids for financial zones. Harmonizes energy.',descHi:'बिस्तर/मेज के नीचे अष्टभुजाकार तांबे के पिरामिड। आर्थिक क्षेत्र हेतु पीतल पिरामिड। ऊर्जा का सामंजस्य।',color:'#FF9933'},
                {title:'Crystal Grid Therapy',titleHi:'क्रिस्टल ग्रिड थेरेपी',desc:'Black tourmaline for EMF, amethyst for neurological calm, clear quartz for amplification, smoky quartz for detox.',descHi:'EMF हेतु ब्लैक टूरमलाइन, तंत्रिका-शांति हेतु एमेथिस्ट, वर्धन हेतु क्लियर क्वार्ट्ज़, विषाहरण हेतु स्मोकी क्वार्ट्ज़।',color:'#8B5CF6'},
                {title:'Furniture Relocation',titleHi:'फर्नीचर स्थानांतरण',desc:'Shift bed/desk 3‑5 feet from GS line. Most immediate remedy with dramatic health improvements.',descHi:'GS रेखा से 3–5 फीट बिस्तर/मेज हटाएँ। नाटकीय स्वास्थ्य-सुधार वाला सर्वांत तत्काल उपचार।',color:'#10B981'},
                {title:'Rock Salt Absorption',titleHi:'शिला-लवण अवशोषण',desc:'Glass bowls in corners absorb negative vibrations and EMF energy. Replace every 10 days.',descHi:'कोनों में कांच के कटोरे नकारात्मक कंपन एवं EMF ऊर्जा अवशोषित करते हैं। हर 10 दिन बदलें।',color:'#06B6D4'},
                {title:'Plant‑Based Purification',titleHi:'पौधा-आधारित शुद्धि',desc:'Snake plant, areca palm, peace lily, Tulsi placed in specific directions according to element.',descHi:'स्नेक प्लांट, एरेका पाम, पीस लिली, तुलसी को तत्वानुसार विशिष्ट दिशाओं में रखें।',color:'#EC4899'},
                {title:'EMF Shielding & Digital Sunset',titleHi:'EMF शील्डिंग एवं डिजिटल सनसेट',desc:'EMF‑shielding bed canopies. Wi‑Fi off at night. Phones 6 feet from beds. 60‑min pre‑sleep device off.',descHi:'EMF-शील्डिंग बिस्तर-कॉनोपी। रात्रि में Wi‑Fi बंद। फोन बिस्तर से 6 फीट दूर। नींद से 60 मिनट पूर्व उपकरण बंद।',color:'#EF4444'},
              ].map((item,idx)=>(<div key={idx} className="bg-[var(--color-bg-glass)] backdrop-blur-sm rounded-2xl p-5 border border-prakash-gold/15 hover:shadow-lg"><div className="w-2 h-2 rounded-full mb-3" style={{backgroundColor:item.color}}/><h3 className="font-serif text-lg text-nidra-indigo font-bold mb-2">{bi(item.title, item.titleHi)}</h3><p className="text-xs text-nidra-indigo/60">{bi(item.desc, item.descHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── FINAL CTA ── */}
        <section className="relative py-24 sm:py-32 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10">
            <div className="max-w-3xl mx-auto text-center">
              <div className="relative rounded-[40px] p-[2px] bg-gradient-to-br from-prakash-gold/30 via-white/10 to-red-400/30 shadow-[0_25px_60px_rgba(0,0,0,0.4)]">
                <div className="rounded-[38px] bg-[var(--color-bg-glass)] backdrop-blur-2xl p-8 sm:p-12 md:p-16 border border-[var(--color-border-soft)] shadow-inner">
                  <h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-[var(--color-hero-fg)] mb-4">{bi('Let AstroVastu Expert K.K. Nagaich Detect & Neutralise Your Geopathic Stress', 'एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच से अपना भू-रोगजनक तनाव पहचान एवं निष्क्रिय कराएँ')}</h2>
                  <p className="text-[var(--color-hero-fg)]/70 text-base sm:text-lg max-w-xl mx-auto mb-10">{bi('Book a private geopathic stress audit covering all 9 sacred practices — performed personally by a 4th‑generation Vastu Guru with 20+ years of clinical practice and 2 Lakh+ clients worldwide.', 'सभी 9 पवित्र प्रथाओं को समेटे एक निजी भू-रोगजनक तनाव ऑडिट बुक करें — 20+ वर्षों के साक्षात् अनुभव एवं 2 लाख+ विश्वव्यापी क्लाइंट्स वाले 4थी पीढ़ी के वास्तु गुरु द्वारा स्वयं संपन्न।')}</p>
                  <Link href="/bookings" className="inline-block px-10 py-5 bg-gradient-to-r from-red-500 via-prakash-gold to-sacred-saffron text-white font-bold rounded-full shadow-[0_10px_40px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_50px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Schedule Your Geopathic Audit →', 'अपना भू-रोग ऑडिट शेड्यूल करें →')}</Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      
      <style>{`@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-15px)}}@keyframes heroLoop{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}`}</style>
    </>
  );
}
