'use client';
import Header from '@/features/shared/components/Header';
import { SoundController } from '@/features/shared/components/SoundController';
import Link from 'next/link';
import { useBi } from '@/lib/i18n/Bilingual';

export default function CrystalColorTherapyPage() {
  const bi = useBi();
  return (
    <>

        {/* ── LOOPING GRADIENT HERO ── */}
        <section className="relative min-h-[85vh] flex items-center justify-center overflow-hidden bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(139,92,246,0.12),transparent_60%)]" />
          <div className="absolute top-20 left-[8%] w-80 h-80 rounded-full bg-gradient-to-br from-violet-400/8 to-transparent backdrop-blur-3xl border border-[var(--color-border-soft)] animate-[float_10s_ease-in-out_infinite]" />
          <div className="absolute bottom-10 right-[5%] w-64 h-64 rounded-full bg-gradient-to-tl from-emerald-400/5 to-transparent backdrop-blur-2xl border border-[var(--color-border-soft)] animate-[float_12s_ease-in-out_infinite_reverse]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10 text-center mt-16">
            <span className="text-prakash-gold uppercase tracking-[0.3em] text-xs sm:text-sm mb-4 block font-semibold">{bi('Advance Treatments · उन्नत उपचार', 'उन्नत उपचार')}</span>
            <h1 className="font-serif text-4xl sm:text-5xl md:text-7xl lg:text-8xl text-[var(--color-hero-fg)] mb-6 leading-tight drop-shadow-2xl"><span className="bg-gradient-to-r from-violet-300 via-emerald-300 to-prakash-gold bg-clip-text text-transparent">{bi('Crystal & Color Therapy', 'स्फटिक एवं रंग चिकित्सा')}</span></h1>
            <p className="text-base sm:text-lg md:text-xl text-[var(--color-hero-fg)]/70 max-w-3xl mx-auto mb-4 px-4 leading-relaxed">{bi('Crystal Grids (Amethyst, Clear Quartz, Black Tourmaline, Rose Quartz, Citrine) · Colour Directional Therapy · Elemental Balancing · Chakra‑Aligned Placement · Room‑by‑Room Colour Prescriptions · EMF Absorption · Emotional & Physical Harmonisation', 'स्फटिक ग्रिड (जामुनिया, स्वच्छ स्फटिक, काला तुर्मलीन, रोज़ स्फटिक, सिट्रीन) · दिशात्मक रंग चिकित्सा · तत्व संतुलन · चक्र-संरेखित स्थापना · कक्षवार रंग-नुस्खे · EMF अवशोषण · भावनात्मक एवं शारीरिक सामंजस्य')}</p>
            <p className="text-sm sm:text-base text-[var(--color-hero-fg)]/50 max-w-2xl mx-auto mb-10">{bi('Sacred crystal and colour energy correction — performed by AstroVastu Expert K.K. Nagaich, 4th generation Guru, MBA, Ex‑CEO — for homes, offices, healing spaces, and spiritual sanctuaries.', 'पवित्र स्फटिक एवं रंग ऊर्जा सुधार — एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा — 4 पीढ़ियों के गुरु, MBA, पूर्व सीईओ — घरों, कार्यालयों, उपचार स्थलों एवं आध्यात्मिक पूजा-स्थलों हेतु।')}</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/bookings" className="px-10 py-5 bg-gradient-to-r from-violet-500 via-emerald-500 to-prakash-gold text-nidra-indigo font-bold rounded-full shadow-[0_10px_30px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_45px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Book Crystal & Colour Consultation', 'स्फटिक एवं रंग परामर्श बुक करें')}</Link><Link href="#practices" className="bg-transparent border-2 border-white text-white hover:bg-white/10 px-10 py-5 rounded-full text-lg font-medium">{bi('Explore Practices ↓', 'उपाय जानें ↓')}</Link></div>
          </div>
        </section>

        {/* ── CRYSTAL + COLOR SCIENCE ── */}
        <section className="py-16 sm:py-24 bg-gradient-to-b from-[var(--color-bg-elevated)] via-vastu-stone/10 to-[var(--color-bg-elevated)] relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('The Science of Light & Earth', 'प्रकाश एवं पृथ्वी का विज्ञान')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Crystal Vibrations & Colour Frequencies – The Two Gentle Giants of Vastu Correction', 'स्फटिक के कंपन एवं रंगों की आवृत्तियाँ – वास्तु सुधार की दो कोमल महाशक्तियाँ')}</h2><p className="text-nidra-indigo/60 max-w-3xl mx-auto text-sm">{bi('Crystals vibrate at specific frequencies — amethyst at 432 Hz for neurological calm, clear quartz at 528 Hz for cellular repair, black tourmaline at 396 Hz for EMF absorption. Each colour wavelength corresponds to a directional element, forming a complete non‑demolition energy‑correction system.', 'स्फटिक निश्चित आवृत्तियों पर कंपित होते हैं — जामुनिया 432 Hz पर (तंत्रिकीय शांति हेतु), स्वच्छ स्फटिक 528 Hz (कोषीय पुनर्निर्माण हेतु), काला तुर्मलीन 396 Hz (EMF अवशोषण हेतु)। प्रत्येक रंग की तरंगदैर्ध्य एक दिशात्मक तत्व से संगत होती है, जो संपूर्ण गैर-तोड़-फोड़ ऊर्जा-सुधार प्रणाली रचती है।')}</p></div>
          </div>
        </section>

        {/* ── 9 SACRED PRACTICES ── */}
        <section id="practices" className="py-16 sm:py-24 bg-[var(--color-bg-elevated)] relative">
          <div className="container mx-auto px-4 sm:px-6 max-w-6xl">
            <div className="text-center mb-14"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Sacred Crystal & Colour Practices', 'पावन स्फटिक एवं रंग उपाय')}</span><h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-nidra-indigo mt-3 mb-4">{bi('Authentic Crystal Grid & Colour Therapy for Elemental Harmony', 'तत्व सामंजस्य हेतु प्रामाणिक स्फटिक ग्रिड एवं रंग चिकित्सा')}</h2><p className="text-nidra-indigo/60 max-w-2xl mx-auto text-sm">{bi('Each practice deploys specific crystals and precise colour wavelengths selected by AstroVastu Expert K.K. Nagaich.', 'प्रत्येक उपाय में एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच द्वारा चयनित विशिष्ट स्फटिक एवं सूक्ष्म रंग-तरंगदैर्ध्य प्रयुक्त होती हैं।')}</p></div>
            <div className="space-y-16">
              {[
                {num:'01',title:'The 5‑Element Crystal Grid (Pancha Mahabhuta Crystal Array)',titleHi:'पंच-तत्व स्फटिक ग्रिड (पंचमहाभूत क्रिस्टल सरणी)',desc:'5 crystals for 5 elements at 5 directional zones: Clear Quartz NE (Water, spiritual amplification), Citrine SE (Fire, abundance), Black Tourmaline SW (Earth, grounding), Aquamarine NW (Air, communication), Amethyst Centre (Space, universal harmony). Each geometrically cut and planetary mantra energised. Annual re‑energisation only.',descHi:'पाँच दिशात्मक क्षेत्रों में पाँच तत्वों हेतु पाँच स्फटिक: स्वच्छ स्फटिक ईशान में (जल, आध्यात्मिक वर्धन), सिट्रीन आग्नेय में (अग्नि, प्रचुरता), काला तुर्मलीन नैर्ऋत्य में (पृथ्वी, स्थिरता), एक्वामरीन उत्तर-पश्चिम में (वायु, संचार), जामुनिया केंद्र में (आकाश, सार्वभौमिक सामंजस्य)। प्रत्येक ज्यामितीय गढ़ाई एवं ग्रह-मंत्रों से संजीवित। केवल वार्षिक पुनः-संजीवन आवश्यक।',features:['5 crystals for 5 elements','Clear Quartz NE, Citrine SE, Black Tourmaline SW','Aquamarine NW, Amethyst Centre','Geometrically cut & mantra energised','Annual re‑energisation only'],featuresHi:['पाँच तत्वों हेतु पाँच स्फटिक','स्वच्छ स्फटिक ईशान, सिट्रीन आग्नेय, काला तुर्मलीन नैर्ऋत्य','एक्वामरीन उत्तर-पश्चिम, जामुनिया केंद्र','ज्यामितीय गढ़ाई एवं मंत्र-संजीवन','केवल वार्षिक पुनः-संजीवन'],color:'#8B5CF6'},
                {num:'02',title:'Black Tourmaline EMF & Geopathic Stress Absorption Protocol',titleHi:'काले तुर्मलीन का EMF एवं भू-रोगी तनाव अवशोषण प्रोटोकॉल',desc:'The single most effective crystal for EMF absorption and geopathic stress neutralisation. One Black Tourmaline in each corner of every room creates an EMF absorption grid. Beside Wi‑Fi routers and electrical panels. Natural self‑discharge — no monthly cleansing. Replace every 12‑18 months upon saturation.',descHi:'EMF अवशोषण एवं भू-रोगी तनाव निवारण हेतु सर्वाधिक प्रभावी एकमात्र स्फटिक। प्रत्येक कक्ष के हर कोण में काला तुर्मलीन EMF-अवशोषण जाल रच देता है। वाई-फाई राउटर एवं इलेक्ट्रिकल पैनल के समीप। प्राकृतिक स्वतः-डिसचार्ज — मासिक शुद्धि की आवश्यकता नहीं। संतृप्ति पर प्रत्येक 12–18 माह में प्रतिस्थापन करें।',features:['One per room corner – complete EMF grid','Beside Wi‑Fi router & electrical panel','Natural self‑discharge – no monthly cleansing','Replace every 12‑18 months upon saturation','Also neutralises geopathic stress radiation'],featuresHi:['प्रत्येक कोण में एक – संपूर्ण EMF जाल','वाई-फाई राउटर एवं इलेक्ट्रिकल पैनल के समीप','प्राकृतिक स्वतः-डिसचार्ज – मासिक शुद्धि नहीं','संतृप्ति पर 12–18 माह में प्रतिस्थापन','भू-रोगी तनाव विकिरण का भी निवारण'],color:'#111111'},
                {num:'03',title:'Amethyst Clusters for Sleep Quality & Neurological Calm',titleHi:'नींद की गुणवत्ता एवं तंत्रिकीय शांति हेतु जामुनिया के गुच्छे',desc:'Amethyst clusters — the crystal form with highest vibrational surface area — placed on bedside table (left side) or under bed in SW corner. Measurably improves sleep onset, reduces nightmares, deepens REM cycles. NE corner amethyst amplifies spiritual clarity. Children\'s NW amethyst reduces hyperactivity. Moonlight cleansing monthly.',descHi:'जामुनिया के गुच्छे — सर्वाधिक कंपन-पृष्ठ क्षेत्रफल वाला स्फटिक रूप — शयन-मेज़ (बाईं ओर) पर या नैर्ऋत्य कोण में बिस्तर के नीचे रखें। नींद की शुरुआत में मापनीय सुधार, दुःस्वप्नों में कमी, REM चक्र गहन होते हैं। ईशान कोण का जामुनिया आध्यात्मिक स्पष्टता वर्धित करता है। बच्चों हेतु उत्तर-पश्चिम में जामुनिया अति-सक्रियता घटाता है। मासिक चाँदनी शुद्धि।',features:['Bedside amethyst cluster for sleep','NE corner amethyst for spiritual clarity','Children\'s NW amethyst for hyperactivity','Moonlight cleansing monthly','Highest vibrational surface area'],featuresHi:['नींद हेतु शयन-मेज़ पर जामुनिया गुच्छा','आध्यात्मिक स्पष्टता हेतु ईशान कोण में जामुनिया','अति-सक्रियता हेतु बच्चों के उत्तर-पश्चिम में जामुनिया','मासिक चाँदनी शुद्धि','सर्वाधिक कंपन-पृष्ठ क्षेत्रफल'],color:'#7C3AED'},
                {num:'04',title:'Rose Quartz Relationship & Emotional Healing Grid',titleHi:'रोज़ स्फटिक – रिश्तों एवं भावनात्मक उपचार ग्रिड',desc:'Rose Quartz sphere in SW master bedroom activates love frequency and harmonises relationship energy. Dual bedside Rose Quartz balances masculine‑feminine energies. Singles: SW Rose Quartz for partnership attraction. Living room East/NE cluster for family harmony. Moonlight cleansing + Sankalpa re‑energisation.',descHi:'मास्टर बेडरूम के नैर्ऋत्य कोण में रोज़ स्फटिक का गोला प्रेम की आवृत्ति जाग्रत करता है एवं रिश्तों की ऊर्जा को सौहार्दपूर्ण बनाता है। दोनों शयन-मेज़ों पर रोज़ स्फटिक पुरुष एवं स्त्री ऊर्जाओं को संतुलित करता है। अविवाहित: जीवनसाथी आकर्षण हेतु नैर्ऋत्य में रोज़ स्फटिक। बैठक कक्ष के पूर्व/ईशान में गुच्छा – पारिवारिक सामंजस्य हेतु। चाँदनी शुद्धि + संकल्प पुनः-संजीवन।',features:['SW master bedroom sphere for harmony','Dual bedside for masculine‑feminine balance','Singles: SW for partnership attraction','Living room E/NE for family harmony','Moonlight + Sankalpa intention'],featuresHi:['सामंजस्य हेतु नैर्ऋत्य मास्टर बेडरूम में गोला','पुरुष-स्त्री ऊर्जा संतुलन हेतु दोनों शयन-मेज़','अविवाहित: जीवनसाथी आकर्षण हेतु नैर्ऋत्य','पारिवारिक सामंजस्य हेतु बैठक कक्ष पूर्व/ईशान में गुच्छा','चाँदनी + संकल्प-संजीवन'],color:'#EC4899'},
                {num:'05',title:'Clear Quartz Master Amplifier – Brahmasthan & Directional Grid',titleHi:'स्वच्छ स्फटिक मास्टर वर्धक – ब्रह्मस्थान एवं दिशात्मक ग्रिड',desc:'Clear Quartz is the programmable master amplifier storing and transmitting any intention. Brahmasthan master crystal coordinates all other crystals. 4 cardinal points: N (wealth), E (health), S (protection), W (creativity). Mantra‑specific programming for each directional point. Monthly sunlight cleansing 3‑4 hours.',descHi:'स्वच्छ स्फटिक प्रोग्राम-योग्य प्रमुख वर्धक है, जो किसी भी संकल्प को संचित एवं संप्रेषित करता है। ब्रह्मस्थान का प्रधान स्फटिक सभी अन्य स्फटिकों का समन्वय करता है। चार मुख्य दिशाएँ: उत्तर (धन), पूर्व (स्वास्थ्य), दक्षिण (सुरक्षा), पश्चिम (रचनात्मकता)। प्रत्येक दिशा-बिंदु हेतु विशिष्ट मंत्र-संजीवन। मासिक 3–4 घंटे धूप-शुद्धि।',features:['Brahmasthan master – grid coordinator','4 cardinal points: N, E, S, W','Mantra‑specific directional programming','Monthly sunlight cleansing (3‑4h)','Programmable – stores any intention'],featuresHi:['ब्रह्मस्थान प्रधान – ग्रिड समन्वयक','चार मुख्य दिशाएँ: उत्तर, पूर्व, दक्षिण, पश्चिम','मंत्र-विशिष्ट दिशा संजीवन','मासिक धूप-शुद्धि (3–4 घंटे)','संकल्प-संचयन योग्य वर्धक'],color:'#E2E8F0'},
                {num:'06',title:'Directional Colour Therapy – Room‑by‑Room Prescription Protocol',titleHi:'दिशात्मक रंग चिकित्सा – कक्षवार नुस्खा प्रोटोकॉल',desc:'NE: white, cream, light yellow, pale blue (Water). SE: warm orange, peach, terracotta, pink (Fire). SW: earthy browns, warm beige, pastel peach (Earth). NW: light grey, sky blue, soft silver (Air). Centre: white, cream, light yellow (Space). A fresh coat of paint in the prescribed colour can activate a weak zone within 48 hours.',descHi:'ईशान: सफेद, क्रीम, हल्का पीला, हल्का नीला (जल)। आग्नेय: गहरा नारंगी, पीच, टेर्राकोटा, गुलाबी (अग्नि)। नैर्ऋत्य: मिट्टी जैसे भूरे, गर्म बेज, हल्का पीच (पृथ्वी)। उत्तर-पश्चिम: हल्का ग्रे, आकाशी नीला, कोमल चाँदी-रंग (वायु)। केंद्र: सफेद, क्रीम, हल्का पीला (आकाश)। निर्धारित रंग में नई पट एक कमजोर क्षेत्र को 48 घंटे के भीतर सक्रिय कर सकता है।',features:['NE: white, cream, pale blue (Water)','SE: warm orange, peach, pink (Fire)','SW: earthy browns, beige (Earth)','NW: light grey, sky blue (Air)','Centre: white, cream (Space – neutral)'],featuresHi:['ईशान: सफेद, क्रीम, हल्का नीला (जल)','आग्नेय: नारंगी, पीच, गुलाबी (अग्नि)','नैर्ऋत्य: मिट्टी-भूरे, बेज (पृथ्वी)','उत्तर-पश्चिम: हल्का ग्रे, आकाशी नीला (वायु)','केंद्र: सफेद, क्रीम (आकाश – तटस्थ)'],color:'#FFD700'},
                {num:'07',title:'Chakra‑Aligned Crystal Placement for Physical & Energetic Wellness',titleHi:'शारीरिक एवं ऊर्जात्मक स्वास्थ्य हेतु चक्र-संरेखित स्फटिक स्थापना',desc:'7 chakras → 7 directional zones → 7 crystals. Root‑SW (Red Jasper), Sacral‑W (Carnelian), Solar‑C (Citrine), Heart‑E (Rose Quartz), Throat‑N (Blue Lace Agate), Third Eye‑NE (Amethyst), Crown‑Brahmasthan (Clear Quartz). Silent 24‑hour healing environment.',descHi:'7 चक्र → 7 दिशात्मक क्षेत्र → 7 स्फटिक। मूलाधार-नैर्ऋत्य (रेड जैस्पर), स्वाधिष्ठान-पश्चिम (कार्नेलियन), मणिपूरक-केंद्र (सिट्रीन), अनाहत-पूर्व (रोज़ स्फटिक), विशुद्ध-उत्तर (ब्लु लेस अगेट), आज्ञा-ईशान (जामुनिया), सहस्रार-ब्रह्मस्थान (स्वच्छ स्फटिक)। निःशब्द 24-घंटे का उपचारात्मक वातावरण।',features:['7 chakras → 7 zones → 7 crystals','Root‑SW, Sacral‑W, Solar‑C, Heart‑E','Throat‑N, Third Eye‑NE, Crown‑Brahmasthan','24‑hour silent healing environment'],featuresHi:['7 चक्र → 7 क्षेत्र → 7 स्फटिक','मूलाधार-नैर्ऋत्य, स्वाधिष्ठान-पश्चिम, मणिपूरक-केंद्र, अनाहत-पूर्व','विशुद्ध-उत्तर, आज्ञा-ईशान, सहस्रार-ब्रह्मस्थान','24-घंटे निःशब्द उपचार वातावरण'],color:'#10B981'},
                {num:'08',title:'Crystal & Colour Integration Protocol – The Combined Amplification Effect',titleHi:'स्फटिक एवं रंग एकीकरण प्रोटोकॉल – संयुक्त वर्धन प्रभाव',desc:'Combined deployment is multiplicative. Citrine + peach walls in SE = 3× fire element amplification. Clear Quartz + cream NE = balanced spiritual energy. Avoid: Amethyst in red room = energetic dissonance. Full elemental audit before any crystal‑colour pairing ensures therapies amplify rather than cancel.',descHi:'संयुक्त प्रयोग गुणक प्रभाव देता है। आग्नेय में सिट्रीन + पीच दीवारें = 3× अग्नि तत्व वर्धन। ईशान में स्वच्छ स्फटिक + क्रीम = संतुलित आध्यात्मिक ऊर्जा। परहेज: लाल कक्ष में जामुनिया = ऊर्जात्मक संघर्ष। किसी भी स्फटिक-रंग युग्मन से पूर्व संपूर्ण तत्व-ऑडिट सुनिश्चित करता है कि उपचार परस्पर निरस्त होने के बजाय वर्धित हों।',features:['Combined deployment = multiplicative','Citrine + peach walls = 3× fire amplification','Clear Quartz + cream NE = balanced spiritual','Avoid: Amethyst in red room = dissonance','Full elemental audit before any pairing'],featuresHi:['संयुक्त प्रयोग = गुणक प्रभाव','सिट्रीन + पीच दीवारें = 3× अग्नि वर्धन','स्वच्छ स्फटिक + क्रीम ईशान = संतुलित आध्यात्मिकता','परहेज: लाल कक्ष में जामुनिया = ऊर्जा संघर्ष','युग्मन से पूर्व संपूर्ण तत्व-ऑडिट'],color:'#FF9933'},
                {num:'09',title:'Crystal Maintenance, Cleansing & Annual Re‑Energisation Protocol',titleHi:'स्फटिक अनुरक्षण, शुद्धि एवं वार्षिक पुनः-संजीवन प्रोटोकॉल',desc:'Black Tourmaline: replace every 12‑18 months (EMF saturation). Clear Quartz & Amethyst: monthly moonlight cleansing. Rose Quartz: moonlight only (no sunlight, no salt water). Citrine: never requires cleansing (self‑discharging). Annual Vastu Shanti Havan collective re‑energisation for all crystals.',descHi:'काला तुर्मलीन: प्रत्येक 12–18 माह में प्रतिस्थापन (EMF संतृप्ति)। स्वच्छ स्फटिक एवं जामुनिया: मासिक चाँदनी शुद्धि। रोज़ स्फटिक: केवल चाँदनी (न धूप, न नमक-जल)। सिट्रीन: शुद्धि की आवश्यकता नहीं (स्वतः-डिसचार्ज)। सभी स्फटिकों हेतु वार्षिक वास्तु शांति हवन से सामूहिक पुनः-संजीवन।',features:['Black Tourmaline: replace 12‑18 months','Clear Quartz & Amethyst: monthly moonlight','Rose Quartz: moonlight only','Citrine: never requires cleansing','Annual Vastu Shanti Havan re‑energisation'],featuresHi:['काला तुर्मलीन: 12–18 माह में प्रतिस्थापन','स्वच्छ स्फटिक एवं जामुनिया: मासिक चाँदनी','रोज़ स्फटिक: केवल चाँदनी','सिट्रीन: कभी शुद्धि आवश्यक नहीं','वार्षिक वास्तु शांति हवन पुनः-संजीवन'],color:'#6366F1'},
              ].map((p,i)=>(
                <div key={i} className={`flex flex-col ${i%2===0?'lg:flex-row':'lg:flex-row-reverse'} gap-8 lg:gap-12 items-start`}>
                  <div className="lg:w-1/3 flex-shrink-0">
                    <div className="relative p-8 rounded-3xl bg-gradient-to-br from-[var(--color-bg-elevated)] via-[var(--color-bg-glass)] to-[var(--color-bg-glass)] backdrop-blur-md border border-prakash-gold/20 shadow-[0_10px_30px_rgba(0,0,0,0.06)] text-center">
                      <div className="absolute top-0 left-0 right-0 h-1.5 rounded-t-3xl" style={{backgroundColor:p.color}}/>
                      <div className="text-6xl font-bold mt-4 mb-2" style={{color:p.color}}>{p.num}</div>
                      <h3 className="font-serif text-xl text-nidra-indigo font-bold">{bi(p.title, p.titleHi).split('(')[0].trim()}</h3>
                      <p className="text-xs text-nidra-indigo/50 mt-1">{bi(p.title, p.titleHi).match(/\(.*?\)/)?.[0]?.replace(/[()]/g,'')}</p>
                    </div>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm sm:text-base text-nidra-indigo/70 leading-relaxed mb-4">{bi(p.desc, p.descHi)}</p>
                    <div className="flex flex-wrap gap-2">{p.features.map((f,j)=><span key={j} className="text-xs px-3 py-1.5 rounded-full border" style={{borderColor:p.color+'30',backgroundColor:p.color+'08',color:p.color}}>{bi(f, p.featuresHi?.[j])}</span>)}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── CRYSTAL & COLOR QUICK REFERENCE ── */}
        <section className="py-16 sm:py-24 bg-vastu-stone/10 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-prakash-gold/30 to-transparent" />
          <div className="container mx-auto px-4 sm:px-6 max-w-5xl">
            <div className="text-center mb-12"><span className="text-sacred-saffron uppercase tracking-[0.2em] text-sm font-semibold">{bi('Quick Reference', 'झलक संदर्भ')}</span><h2 className="font-serif text-3xl sm:text-4xl text-nidra-indigo mt-3 mb-4">{bi('Crystal & Colour Reference Matrices — Room by Room, Direction by Direction', 'स्फटिक एवं रंग संदर्शिका – कक्षवार, दिशावार')}</h2></div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {[
                {entity:'Northeast (Ishanya)',entityHi:'ईशान (उत्तर-पूर्व)',color:'Soft white, cream, pale yellow, light blue',colorHi:'कोमल सफेद, क्रीम, हल्का पीला, हल्का नीला',crystal:'Clear Quartz, Amethyst, Sodalite',crystalHi:'स्वच्छ स्फटिक, जामुनिया, सोडालाइट',purpose:'Spiritual amplification, mental clarity, divine connection.',purposeHi:'आध्यात्मिक वर्धन, मानसिक स्पष्टता, दैवीय जुड़ाव।',colorHex:'#FEF3C7'},
                {entity:'East',entityHi:'पूर्व',color:'White, light green, pale blue, cream',colorHi:'सफेद, हल्का हरा, हल्का नीला, क्रीम',crystal:'Green Aventurine, Rose Quartz, Aquamarine',crystalHi:'हरा एवेन्च्यूरिन, रोज़ स्फटिक, एक्वामरीन',purpose:'Health, growth, new beginnings.',purposeHi:'स्वास्थ्य, वृद्धि, नई शुरुआत।',colorHex:'#ECFDF5'},
                {entity:'Southeast (Agneya)',entityHi:'आग्नेय (दक्षिण-पूर्व)',color:'Warm orange, peach, terracotta, soft pink',colorHi:'गहरा नारंगी, पीच, टेर्राकोटा, कोमल गुलाबी',crystal:'Citrine, Carnelian, Red Jasper',crystalHi:'सिट्रीन, कार्नेलियन, रेड जैस्पर',purpose:'Fire activation, cash flow, metabolism.',purposeHi:'अग्नि जागरण, धन-प्रवाह, चयापचय।',colorHex:'#FED7AA'},
                {entity:'South',entityHi:'दक्षिण',color:'Coral red, soft pink, peach, light maroon',colorHi:'मूंगा-लाल, कोमल गुलाबी, पीच, हल्का मैरून',crystal:'Red Coral, Garnet, Carnelian',crystalHi:'मूंगा, गार्नेट, कार्नेलियन',purpose:'Fame, recognition, social standing.',purposeHi:'यश, पहचान, सामाजिक प्रतिष्ठा।',colorHex:'#FECACA'},
                {entity:'Southwest (Nairutya)',entityHi:'नैर्ऋत्य (दक्षिण-पश्चिम)',color:'Earthy browns, warm beige, pastel peach, light pink',colorHi:'मिट्टी जैसे भूरे, गर्म बेज, हल्का पीच, हल्का गुलाबी',crystal:'Black Tourmaline, Smoky Quartz, Hematite',crystalHi:'काला तुर्मलीन, स्मोकी स्फटिक, हेमाटाइट',purpose:'Stability, relationships, grounding.',purposeHi:'स्थिरता, रिश्ते, पृथ्वी से जोड़ाव (ग्राउंडिंग)।',colorHex:'#FDE68A'},
                {entity:'West',entityHi:'पश्चिम',color:'Light blue, silver, grey, white, pale pink',colorHi:'हल्का नीला, चाँदी-रंग, ग्रे, सफेद, हल्का गुलाबी',crystal:'Blue Lace Agate, Lapis Lazuli, Aquamarine',crystalHi:'ब्लु लेस अगेट, लाजवर्द, एक्वामरीन',purpose:'Creativity, children, learning.',purposeHi:'रचनात्मकता, संतान, शिक्षण।',colorHex:'#E0F2FE'},
                {entity:'Northwest (Vayavya)',entityHi:'वायव्य (उत्तर-पश्चिम)',color:'Sky blue, light grey, soft silver, pale green',colorHi:'आकाशी नीला, हल्का ग्रे, कोमल चाँदी-रंग, हल्का हरा',crystal:'Amazonite, Fluorite, Labradorite',crystalHi:'एमेज़ोनाइट, फ्लोराइट, लेब्राडोराइट',purpose:'Communication, movement, client flow.',purposeHi:'संचार, गतिविधि, ग्राहक-प्रवाह।',colorHex:'#F0F9FF'},
                {entity:'North (Kubera)',entityHi:'कुबेर (उत्तर)',color:'Light green, pale blue, soft yellow, white',colorHi:'हल्का हरा, हल्का नीला, कोमल पीला, सफेद',crystal:'Pyrite, Green Jade, Citrine',crystalHi:'पाइराइट, ग्रीन जेद, सिट्रीन',purpose:'Wealth, career, opportunities.',purposeHi:'धन, करियर, अवसर।',colorHex:'#D1FAE5'},
                {entity:'Centre (Brahmasthan)',entityHi:'केंद्र (ब्रह्मस्थान)',color:'White, cream, light yellow — neutral palette',colorHi:'सफेद, क्रीम, हल्का पीला – तटष्ठ रंग-पैलेट',crystal:'Clear Quartz (master), Selenite, Moonstone',crystalHi:'स्वच्छ स्फटिक (प्रधान), सेलेनाइट, चाँदमणी',purpose:'Universal balance, harmony, cosmic connection.',purposeHi:'सार्वभौमिक संतुलन, सामंजस्य, दिव्य जुड़ाव।',colorHex:'#FFFBEB'},
              ].map((item,idx)=>(<div key={idx} className="bg-[var(--color-bg-glass)] backdrop-blur-sm rounded-2xl p-5 border border-prakash-gold/15 hover:shadow-lg"><div className="flex items-center gap-2 mb-2"><div className="w-4 h-4 rounded-full" style={{backgroundColor:item.colorHex}}/><h3 className="font-serif text-lg text-nidra-indigo font-bold">{bi(item.entity, item.entityHi)}</h3></div><p className="text-xs text-nidra-indigo/50 mt-1"><strong>{bi('Colours:', 'रंग:')}</strong> {bi(item.color, item.colorHi)}</p><p className="text-xs text-nidra-indigo/50 mt-1 mb-2"><strong>{bi('Crystals:', 'स्फटिक:')}</strong> {bi(item.crystal, item.crystalHi)}</p><p className="text-xs text-nidra-indigo/60">{bi(item.purpose, item.purposeHi)}</p></div>))}
            </div>
          </div>
        </section>

        {/* ── FINAL CTA ── */}
        <section className="relative py-24 sm:py-32 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-[var(--color-hero-1)] via-[var(--color-hero-2)] to-[var(--color-hero-1)] bg-[length:400%_400%] animate-[heroLoop_12s_ease_infinite]" />
          <div className="container mx-auto px-4 sm:px-6 relative z-10">
            <div className="max-w-3xl mx-auto text-center">
              <div className="relative rounded-[40px] p-[2px] bg-gradient-to-br from-prakash-gold/30 via-white/10 to-violet-400/30 shadow-[0_25px_60px_rgba(0,0,0,0.4)]">
                <div className="rounded-[38px] bg-[var(--color-bg-glass)] backdrop-blur-2xl p-8 sm:p-12 md:p-16 border border-[var(--color-border-soft)] shadow-inner">
                  <h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-[var(--color-hero-fg)] mb-4">{bi('Let AstroVastu Expert K.K. Nagaich Design Your Crystal & Colour Grid', 'एस्ट्रोवास्तु एक्सपर्ट के. के. नागाइच से रचवाइए अपनी स्फटिक एवं रंग ग्रिड')}</h2>
                  <p className="text-[var(--color-hero-fg)]/70 text-base sm:text-lg max-w-xl mx-auto mb-10">{bi('Every space has a unique elemental signature. Book a private Crystal & Color Therapy consultation — performed personally by a 4th‑generation Vastu Guru, MBA, Ex‑CEO with 20+ years of clinical practice and 2 Lakh+ clients worldwide.', 'हर स्थान की अपनी विशिष्ट तत्व-छाप होती है। स्फटिक एवं रंग चिकित्सा का निजी परामर्श बुक करें — 4 पीढ़ियों के वास्तु गुरु, MBA, पूर्व सीईओ, 20+ वर्षों के नैदानिक अनुभव एवं विश्वभर में 2 लाख+ क्लाइंट्स वाले के. के. नागाइच द्वारा व्यक्तिगत रूप से संपन्न।')}</p>
                  <Link href="/bookings" className="inline-block px-10 py-5 bg-gradient-to-r from-violet-500 via-emerald-500 to-prakash-gold text-nidra-indigo font-bold rounded-full shadow-[0_10px_40px_rgba(232,185,96,0.4)] hover:shadow-[0_20px_50px_rgba(255,153,51,0.5)] transition-all text-lg">{bi('Schedule Your Crystal & Colour Consultation →', 'अपना स्फटिक एवं रंग परामर्श बुक करें →')}</Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      
      <style>{`@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-15px)}}@keyframes heroLoop{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}`}</style>
    </>
  );
}
